- optaplanner-openshift-worker-rostering-gwtui/pom.xml
Limiting the memory of the compiler to -Xmx300m and setting the localWorker to 1 seems to keep the process within the OpenShift Online instance limits.
> Openshift compilation test

- pom.xml
We need to give the GWT compiler a bit more memory. This build does work on my OpenShift Online instance (with my BuildConfig). Let's merge this one first, I'll add the OpenShit template as part of issue #3 .
> Upped max-memory for GWT compiler.

- openshift/templates/optashift-employee-rostering-template.yaml
I still need to edit the README.doc; I don't know what instructions to put for it. However, I got it running on my local OpenShift instance.
> PLANNER-918: Removed the openshift template limitations

- optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/calendar/Calendar.java
- optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/canvas/ColorUtils.java
- optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/common/TimeoutRestCaller.java
- optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/employee/EmployeeDrawable.java
@ge0ffrey Let me know what you think; I modified it so a single click without shift key pressed down cycles employee availability (red -> yellow -> green -> gray -> red -> ...). If you single click with shift key pressed down, you get the original popup. I could put an embedded widget that you can click, but that can pose an issue for users with smaller screens.
> PLANNER-944: Single-Click to change employee avaliability, Shift-Click for more complex edits

- optashift-employee-rostering-benchmark/src/main/java/org/optaplanner/openshift/employeerostering/benchmark/OptaShiftEmployeeRosteringBenchmarkApp.java
- optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/calendar/ShiftData.java
- optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/calendar/ShiftDrawable.java
- optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/calendar/TemplateShiftEditForm.java
- optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/calendar/twodayview/TwoDayViewPresenter.java
- optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/spot/SpotDataFetchable.java
- optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/tenant/TenantConfigurationEditor.java.orig
- optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/tenant/TenantTemplateFetchable.java
- optashift-employee-rostering-gwtui/src/main/resources/org/optaplanner/openshift/employeerostering/gwtui/client/calendar/TemplateShiftEditForm.html
- optashift-employee-rostering-gwtui/src/main/resources/org/optaplanner/openshift/employeerostering/gwtui/client/tenant/TenantConfigurationEditor.html
- optashift-employee-rostering-server/src/main/java/org/optaplanner/openshift/employeerostering/server/lang/parser/ShiftFileParser.java
- optashift-employee-rostering-server/src/main/java/org/optaplanner/openshift/employeerostering/server/roster/RosterGenerator.java
- optashift-employee-rostering-server/src/main/java/org/optaplanner/openshift/employeerostering/server/shift/ShiftRestServiceImpl.java
- optashift-employee-rostering-server/src/main/resources/org/optaplanner/openshift/employeerostering/server/solver/employeeRosteringScoreRules.drl
- optashift-employee-rostering-shared/src/main/java/org/optaplanner/openshift/employeerostering/shared/lang/tokens/OptionalEmployee.java
- optashift-employee-rostering-shared/src/main/java/org/optaplanner/openshift/employeerostering/shared/lang/tokens/ShiftInfo.java
- optashift-employee-rostering-shared/src/main/java/org/optaplanner/openshift/employeerostering/shared/shift/Shift.java
- optashift-employee-rostering-shared/src/main/java/org/optaplanner/openshift/employeerostering/shared/shift/view/ShiftView.java
- optashift-employee-rostering-shared/src/main/java/org/optaplanner/openshift/employeerostering/shared/tenant/TenantConfiguration.java
The main functionality is implemented; But I still need to add more visual indicators to indicate when the employee is not the rotation employee in the spot and employee roster. @ge0ffrey can you verify I did the drools rule correctly?
> PLANNER-943: Allow users to specify a default employee for a shift

- optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/pages/spotroster/ShiftBlob.java
- optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/pages/spotroster/ShiftBlobView.java
- optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/pages/spotroster/SpotRosterPage.java
- optashift-employee-rostering-gwtui/src/main/resources/org/optaplanner/openshift/employeerostering/gwtui/client/pages/spotroster/SpotRosterPage.css
- optashift-employee-rostering-server/src/main/java/org/optaplanner/openshift/employeerostering/server/roster/RosterRestServiceImpl.java
- optashift-employee-rostering-shared/src/main/java/org/optaplanner/openshift/employeerostering/shared/roster/RosterState.java
Historic shifts are not visible in the current implementation (as there are none currently), but would look have no outline
Pinning a shift cause a pin to appear next to the shift text
Published shifts have a solid line, draft shifts have a dotted line
> PLANNER-1055: Added visual indication of Historic, Published and Draft shifts

- optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/common/TableRow.java
- optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/employee/EmployeeSubform.java
- optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/skill/SkillSubform.java
- optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/spot/SpotSubform.java
You can switch between input elements using tab, type into the select box to find and select skills, and click on save/cancel/whatever using enter
> PLANNER-1047: Auto-focus on first input element when editing/creating a Skill/Employee/Spot

- optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/common/LocalDateTimePicker.java
- optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/pages/spotroster/ShiftBlobPopoverContent.java
- optashift-employee-rostering-gwtui/src/main/resources/org/optaplanner/openshift/employeerostering/gwtui/client/common/LocalDateTimePicker.css
- optashift-employee-rostering-gwtui/src/main/resources/org/optaplanner/openshift/employeerostering/gwtui/client/common/LocalDateTimePicker.html
- optashift-employee-rostering-gwtui/src/main/resources/org/optaplanner/openshift/employeerostering/gwtui/client/pages/spotroster/ShiftBlobPopoverContent.html
- optashift-employee-rostering-shared/src/main/java/org/optaplanner/openshift/employeerostering/shared/common/GwtJavaTimeWorkaroundUtil.java
-Created a widget that uses `input[date] + input[time]` to be a `LocalDateTime` Widget (in theory, should fall-back to text input okay)
-Removed RotationEmployee from SpotPopoverForm
-Allow setting the Employee if the shift is not pinned
> Fixed SpotPopoverForm

- optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/pages/employeeroster/EmployeeRosterViewport.java
- optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/pages/spotroster/ShiftBlobPopoverContent.java
- optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/pages/spotroster/SpotRosterViewport.java
- optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/rostergrid/view/SubLaneView.java
Due to `click` being fired on the end of drag events, needed to use a complicated `mousedown`, `mousemove`, `mouseup` device to check if the user clicked without dragging.
> Use single click to add shifts; fixed delete in popup

- README.adoc
Includes a single change in POM which shouldn't break the current command-line approach.
> Update Readme with SuperDevMode instructions for IDEA

- optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/viewport/DateTimeViewport.java
- optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/viewport/availabilityroster/AvailabilityRosterPageViewport.java
- optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/viewport/grid/DateSpan.java
- optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/viewport/grid/DateTimeHeader.java
- optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/viewport/rotation/RotationPageViewport.java
- optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/viewport/shiftroster/ShiftRosterPageViewport.java
- optashift-employee-rostering-gwtui/src/main/resources/org/optaplanner/openshift/employeerostering/gwtui/client/app/AppView.less
- optashift-employee-rostering-gwtui/src/main/resources/org/optaplanner/openshift/employeerostering/gwtui/client/header/HeaderView.html
- optashift-employee-rostering-gwtui/src/main/resources/org/optaplanner/openshift/employeerostering/gwtui/client/header/MenuView.html
- optashift-employee-rostering-gwtui/src/main/resources/org/optaplanner/openshift/employeerostering/gwtui/client/viewport/grid/DateSpan.html
- optashift-employee-rostering-gwtui/src/main/resources/org/optaplanner/openshift/employeerostering/gwtui/public/viewport.less
This PR fixes:
- Header width (now navbar extends the entire screen, instead of stopping 20px before)
- Icon spacing on dates
- Added left margin to spot/employee names in roster screens
- Fixed Date Font
> PLANNER-1097: Fixed font and spacing issues

- optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/gwtjackson/HardMediumSoftLongScoreJsonDeserializer.java
- optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/gwtjackson/HardMediumSoftLongScoreJsonSerializer.java
- optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/viewport/RosterToolbar.java
- optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/rebind/OptaShiftRosteringGwtJacksonConfiguration.java
- optashift-employee-rostering-server/src/main/resources/org/optaplanner/openshift/employeerostering/server/solver/employeeRosteringScoreRules.drl
- optashift-employee-rostering-shared/src/main/java/org/optaplanner/openshift/employeerostering/shared/roster/Roster.java
- optashift-employee-rostering-shared/src/main/java/org/optaplanner/openshift/employeerostering/shared/roster/view/AbstractRosterView.java
- optashift-employee-rostering-shared/src/main/java/org/optaplanner/openshift/employeerostering/shared/shift/Shift.java
To try it out:
- open a dataset, solve it and notice that all shifts get assigned
- now pick a date and start adding new shifts for a spot there. Add so many shifts, that there are more shifts on that date then there are employees. Click solve. Notice that it still finds a schedule with no hard constraints broken, but now there are medium constraints broken: a few shifts didn't get assigned.
@Christopher-Chianelli Can you visualize the medium score in the UI too? And the indictement work will make the unassigned shifts stick out like a soar thumb, of course.
> Overconstrained planning

- optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/viewport/availabilityroster/AvailabilityGridObject.java
- optashift-employee-rostering-gwtui/src/main/resources/org/optaplanner/openshift/employeerostering/gwtui/client/viewport/availabilityroster/AvailabilityGridObject.css
- optashift-employee-rostering-gwtui/src/main/resources/org/optaplanner/openshift/employeerostering/gwtui/client/viewport/availabilityroster/AvailabilityGridObject.html
- optashift-employee-rostering-gwtui/src/main/resources/org/optaplanner/openshift/employeerostering/gwtui/public/viewport.less
Allow people to change the availability type via "traffic lights" at the bottom and delete it by clicking the "X" in the top right corner
> PLANNER-1065: Made Employee Availability editing more steamlined

- employee-rostering-gwtui/src/main/java/org/optaweb/employeerostering/gwtui/client/viewport/shiftroster/IconContainer.java
- employee-rostering-gwtui/src/main/java/org/optaweb/employeerostering/gwtui/client/viewport/shiftroster/ShiftGridObject.java
- employee-rostering-gwtui/src/main/resources/org/optaweb/employeerostering/gwtui/client/viewport/shiftroster/IconContainer.css
- employee-rostering-gwtui/src/main/resources/org/optaweb/employeerostering/gwtui/public/viewport.less
For Icons, if it overflows, you can scroll to see the rest (no scrollbar is shown) (we might be able to indicate this using a shadow). I added a colour scheme: -Hard -> red, -Medium -> yellow, -Soft -> gray, ZERO -> light green, +Soft -> green, +Medium (impossible currently) -> light blue, +Hard (impossible currently) -> purple (modifiable via CSS). The shades get more/less strong depending on how positive/negative the scores are, up to a limit, linearly.
> PLANNER-1173: Fixed indictment issues

- optashift-employee-rostering-webapp/pom.xml
Increasing to two minutes which should satisfy the kieAllBuild.
> Increase cargo deployment timeout

- employee-rostering-docs/src/main/asciidoc/Introduction/SystemProperties/SystemProperties-section.adoc
- employee-rostering-server/src/main/filtered-resources/META-INF/orm.xml
- employee-rostering-server/src/main/filtered-resources/META-INF/persistence.xml
- pom.xml
Hibernate 5 use TABLE id generation for MySQL since it doesn't support sequences. This is very slow,
making it take longer than 300s to generate the example data and start the application. Instead, it
should use IDENTITY, which allows it to generate all the example data in 75s (boot takes 122s in total).
By default, org.optaweb.employeerostering.persistence.id.generator has value AUTO.
Depends on #188, since MySQL have the same warnings
> PLANNER-1221: To decrease deployment time on MySQL, allowed user to select generation stategy

- pom.xml
Let's keep the cargo version used throughout the kiegroup repos build consistent.
This is related to https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/854
For more context:
At the moment there are 2 outdated versions of cargo-maven2-plugin used in our [daily build](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/dailyBuild/job/kieAllBuild-master/) We need to upgrade to latest version of the plugin to be able to run tests with wildfly14 that community is upgrading to.
> Use latest version of cargo-maven2-plugin

- .gitignore
- .travis.yml
- employee-rostering-gwtui/pom.xml
- employee-rostering-webapp/pom.xml
- pom.xml
- configures JaCoCo code coverage, including integration tests
- uses travis to run tests and upload code quality statistics to sonarcloud.io
- after we give it a try, the JaCoCo configuration will be moved to kie-parent to push it to other projects too
> [PLANNER-1292] Provide code quality metrics by sonarcloud.io

- pom.xml
java agent approach (the default one for jacoco) clashes with GWTMockito resulting in zero measured test coverage. Offline instrumentation of unit tests avoids this issue. Jacoco agent remains being used for integration tests, though.
@Christopher-Chianelli please review and merge if you agree and builds are green.
> PLANNER-1384 Use offline instrumentation to support GWTMockito coverage

- pom.xml
Companion to https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/898 to keep the plugin versions in sync
> Update to latest cargo-maven2-plugin

- employee-rostering-benchmark/pom.xml
- employee-rostering-gwtui/pom.xml
- employee-rostering-restclient/pom.xml
- employee-rostering-server/pom.xml
- employee-rostering-shared/pom.xml
- pom.xml
Improvements in POMs after adopting `kie-parent` in #210. For the most part it replaces `javax.javaee-api` with JBoss Spec APIs taken from https://github.com/jboss/jboss-javaee-specs/blob/master/pom.xml#L91.
Part of this commit fixes a GWT compilation classpath problem described in https://github.com/kiegroup/optaweb-employee-rostering/pull/210#issuecomment-439114090. I originally thought it breaks SuperDevMode but it was a local issue that I resolved by `rm -r /tmp`.
Adresses https://issues.jboss.org/browse/PLANNER-1358.
> PLANNER-1358: Align versions with kie-parent and jboss-ip-bom

- employee-rostering-server/src/main/filtered-resources/META-INF/persistence.xml
Reason: MySQL has a poor AUTO id generator, but it used to have a good one, so
setting the magic property to false increases the speed by a factor of at least
3.
> PLANNER-1442: Add Magic Property that makes MySQL goes faster

- employee-rostering-frontend/src/setupTests.ts
- employee-rostering-frontend/src/store/roster/operations.ts
- employee-rostering-frontend/src/store/roster/roster.test.ts
- employee-rostering-frontend/src/store/tenant/tenant.test.ts
- employee-rostering-frontend/src/ui/components/ScoreDisplay.test.tsx
- employee-rostering-frontend/src/ui/components/ScoreDisplay.tsx
- employee-rostering-frontend/src/ui/components/__snapshots__/ScoreDisplay.test.tsx.snap
- employee-rostering-frontend/src/ui/components/__snapshots__/ServerSideExceptionDialog.test.tsx.snap
- employee-rostering-frontend/src/ui/components/calendar/ReactBigCalendarOverrides.css
- employee-rostering-frontend/src/ui/pages/availability/AvailabilityRosterPage.tsx
- employee-rostering-frontend/src/ui/pages/availability/__snapshots__/AvailabilityRosterPage.test.tsx.snap
- employee-rostering-frontend/src/ui/pages/shift/ShiftEvent.test.tsx
- employee-rostering-frontend/src/ui/pages/shift/ShiftEvent.tsx
- employee-rostering-frontend/src/ui/pages/shift/ShiftRosterPage.tsx
- employee-rostering-frontend/src/ui/pages/shift/__snapshots__/ShiftEvent.test.tsx.snap
- employee-rostering-frontend/src/ui/pages/shift/__snapshots__/ShiftRosterPage.test.tsx.snap
- employee-rostering-frontend/translations/en/ScoreDisplay.yaml
Note: I modified the mock translate to also show the params passed
to translate (so the test can verify the correct params are passed into
translate, instead of only verifying the key). This modified some
of the other snapshots.
Another note: for missing translations when the language is set to cmn (or any other language), it will use the English translation as a fallback.
> PLANNER-1699: Fix UI Regressions; show score; add pin icon for pinned shifts

- employee-rostering-frontend/.eslintignore
Some auto-generated .gitignore files are being linted, causing errors. This make eslint also ignore them.
> Add a .eslintignore to ignore files in cypress/.gitignore

- employee-rostering-backend/pom.xml
Jira: https://issues.jboss.org/browse/PLANNER-1727
Fixes `Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException` exception when run on Java 11.
> Add excluded JAXB dependencies for Java 11

- employee-rostering-frontend/pom.xml
Requires: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1117
BXMSPROD-580
> BXMSPROD-580: frontend-maven-plugin version pointing to the centralised one

- employee-rostering-frontend/.eslintrc.json
- employee-rostering-frontend/cypress/.eslintrc.json
- employee-rostering-frontend/cypress/plugins/index.js
- employee-rostering-frontend/cypress/support/index.js
- employee-rostering-frontend/src/i18n.ts
- employee-rostering-frontend/src/store/availability/operations.ts
- employee-rostering-frontend/src/store/roster/operations.ts
- employee-rostering-frontend/src/store/roster/roster.test.ts
- employee-rostering-frontend/src/store/shift/KindaShiftView.ts
- employee-rostering-frontend/src/store/shift/operations.ts
- employee-rostering-frontend/src/store/tenant/operations.ts
- employee-rostering-frontend/src/ui/Alerts.tsx
- employee-rostering-frontend/src/ui/components/Background.tsx
- employee-rostering-frontend/src/ui/components/DataTable.test.tsx
- employee-rostering-frontend/src/ui/components/DataTable.tsx
- employee-rostering-frontend/src/ui/components/MultiTypeaheadSelectInput.test.tsx
- employee-rostering-frontend/src/ui/components/MultiTypeaheadSelectInput.tsx
- employee-rostering-frontend/src/ui/components/TypeaheadSelectInput.test.tsx
- employee-rostering-frontend/src/ui/components/TypeaheadSelectInput.tsx
- employee-rostering-frontend/src/ui/header/Toolbar.tsx
- employee-rostering-frontend/src/ui/pages/availability/AvailabilityRosterPage.test.tsx
- employee-rostering-frontend/src/ui/pages/availability/AvailabilityRosterPage.tsx
- employee-rostering-frontend/src/ui/pages/shift/ShiftEvent.tsx
- employee-rostering-frontend/src/util/ImmutableCollectionOperations.ts
https://issues.jboss.org/browse/PLANNER-1732
For code style and project configuration consistency it is important to unify `.eslintrc.json` between Vehicle Routing and Employee Rostering.
Some time ago I have introduced the airbnb ESLint config (#251) but I've given it a low priority to avoid introducing big changes. Now's the time to take a step further and give it the top priority.
In the next step I'd like to eliminate most of the exceptions to the style (disabled rules).
> PLANNER-1732: Give Airbnb config highest priority

- employee-rostering-frontend/docker/Dockerfile
- provision.sh
OpenShift Online complains about a build with docker strategy for the
frontend. However backend build with the same strategy is OK. The only
difference is that frontend build defines an environment variable with
backend URL. The attempt to create the build failed with:
error: failed to set env: admission webhook "validate.build.create" denied
the request: Builds with docker strategy are prohibited on this cluster
Removing the enviroment variable makes the build work (even thought it
still uses the docker strategy ¯\_(ツ)_/¯). Might be an OpenShift bug.
The same error as above is produced by:
oc set env bc/frontend BACKEND_URL=http://backend:8080
so maybe it's just that docker builds can't have environment variables.
> Make http://backend:8080 default BACKEND_URL in frontend Dockerfile

- employee-rostering-frontend/cypress.json
- employee-rostering-frontend/package.json
Jenkins jobs expect test results to be stored in
**/target/-reports/TEST-.xml
The same change goes into VRP as well:
https://github.com/kiegroup/optaweb-vehicle-routing/pull/229
> [DO NOT MERGE] Place all frontend test reports in a single subdirectory

- employee-rostering-frontend/pom.xml
https://issues.jboss.org/browse/RHDM-1129
depends on
- https://issues.jboss.org/browse/BXMSPROD-597 https://github.com/kiegroup/optaweb-employee-rostering/pull/336
- and https://issues.jboss.org/browse/BXMSPROD-580 https://github.com/kiegroup/optaweb-employee-rostering/pull/330
> RHDM-1129: locktt execution added to productized profile, prepare-package phase

- employee-rostering-frontend/pom.xml
This is needed for the w2k16 Jenkins jobs to build; the older repository doesn't contain win-x64/node.exe.
> Update node version to v11.6.0

- pom.xml
Depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1129.
> Remove Springfox dependency management

- employee-rostering-frontend/pom.xml
This is needed for the w2k16 Jenkins jobs to build; the older repository doesn't contain win-x64/node.exe.
> [7.30.x] Update node version to v11.6.0

- employee-rostering-frontend/package-lock.json
- employee-rostering-frontend/package.json
- employee-rostering-frontend/pom.xml
* BXMSPROD-597: frontend project locktt execution improved
* lock-treatment-tool added to dev-dependencies
* locktt script added
* pom execution changed to npm run locktt
* BXMSPROD-597: -- added to npm run locktt
(cherry picked from commit 91b208b9b0f883b586e28130e503daecf742c0e8)
> [7.30.x] BXMSPROD-597: frontend project locktt execution improved (#336)

- employee-rostering-backend/src/main/resources/application.properties
The Spring `application.properties` file in the backend assumes that deployments will only be to a cluster of docker containers. Allow the env var `DATABASE_HOST` to be injected into `spring.datasource.url` to give some flexibility for production deployments involving a postgres database
> backend: allow postgres host to be specified

- employee-rostering-frontend/pom.xml
This should restore coverage for the frontend module.
> Remove unnecessary profile for defining sonar-related properties

- Dockerfile
Found in the CI builds run by @opengovsg
> Fix missed `optaweb-` prefix in Dockerfile

- README.adoc
- Add Quick Start section
- Add section on setting up developer environment
> README: rework for developer onboarding

- optaweb-employee-rostering-frontend/src/ui/pages/rotation/RotationPage.tsx
- optaweb-employee-rostering-frontend/src/ui/pages/shift/ShiftEvent.test.tsx
- optaweb-employee-rostering-frontend/src/ui/pages/shift/ShiftEvent.tsx
- optaweb-employee-rostering-frontend/src/ui/pages/shift/ShiftRosterPage.tsx
- optaweb-employee-rostering-frontend/src/ui/pages/shift/__snapshots__/ShiftEvent.test.tsx.snap
It is somewhat common to have multiple people scheduled within the same
time period of a roster, so introduce a button in ShiftPopupHeader (and
template equivalent) that allows the quick copying of shifts
- Popup headers: Create a button that invokes an `onCopy()` callback
- make this optional for ShiftPopupHeader usage in
AvailabilityRosterPage as it makes little sense in the user-level
view to copy a slot with either the same user or nobody assigned
(the latter because the copied slot then disappears from view)
- Implement callbacks for RotationPage and ShiftRosterPage
> Allow copying of shifts

- optaweb-employee-rostering-frontend/src/i18n.ts
Locales influence the first day of the week, amongst other things.
While the US, Canada and Japan start the week on Sunday, many other
places start it on Monday.
To avoid ambiguity, bring all locales into moment. This results in
an inconsistency between moment and date-fns (and react-datepicker),
which we can reasonably bear with for now
> moment: bring in all locales

- .travis.yml
- pom.xml
`mvn generate-resources -Psonarcloud-analysis` runs an Ant task that
aggregates reports from individual modules but this project doesn't seem
to be configured correctly for code coverage aggregation.
Adding the report goal fixes code coverage analysis for individual
modules because it generates a JaCoCo XML report in each module that can
be understood by Sonar scanner.
Radek will fix report aggregation later.
> Fix Sonar code coverage analysis

- optaweb-employee-rostering-frontend/pom.xml
They are now managed by kie-parent.
PR group:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1273
- https://github.com/kiegroup/appformer/pull/943
- https://github.com/kiegroup/droolsjbpm-integration/pull/2064
- https://github.com/kiegroup/kie-wb-common/pull/3269
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/296
- https://github.com/kiegroup/optaweb-employee-rostering/pull/425
> BXMSPROD-741: Remove Node and npm versions

- optaweb-employee-rostering-backend/pom.xml
- optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/service/roster/RosterController.java
- optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/util/ShiftRosterXlsxFileIO.java
- optaweb-employee-rostering-frontend/public/assets/translations/en/ExportScheduleModal.yaml
- optaweb-employee-rostering-frontend/public/assets/translations/en/ShiftRosterPage.yaml
- optaweb-employee-rostering-frontend/src/store/contract/selectors.ts
- optaweb-employee-rostering-frontend/src/store/employee/selectors.ts
- optaweb-employee-rostering-frontend/src/store/skill/selectors.ts
- optaweb-employee-rostering-frontend/src/store/spot/selectors.ts
- optaweb-employee-rostering-frontend/src/ui/pages/shift/CurrentShiftRosterPage.tsx
- optaweb-employee-rostering-frontend/src/ui/pages/shift/ExportScheduleModal.tsx
- optaweb-employee-rostering-frontend/src/ui/pages/shift/ShiftRosterPage.tsx
- optaweb-employee-rostering-frontend/src/ui/pages/shift/__snapshots__/ShiftRosterPage.test.tsx.snap
Current format is:
Start, End, Employee
with the following caveats to maximize human readability:
- Shifts with the same date and time in the same spot don't have their date/time repeated
- Employee(s) are 1 line under date/time
Ex:
Start,       End,           Employee
date 1,     date 2,
Amy
Bob
date 3,     date 4,
Charlie
> PLANNER-1958: Allow exporting of Shift Roster to Excel

- .travis.yml
- pom.xml
The reporting is done in the sonarcloud-analysis profile in the kie-parent based on a single file every module appends coverage data to.
> Restore cross-module coverage measurement

- runOnOpenShift.sh
Made runOnOpenShift.sh to store configurations into Deployments instead of DeploymentsConfig.
The same fix as for VRP, see #334
@Christopher-Chianelli @yurloc
> Change configuration to new OCP 4.5.1 standard

- optaweb-employee-rostering-frontend/package-lock.json
- optaweb-employee-rostering-frontend/package.json
- optaweb-employee-rostering-frontend/src/ui/pages/rotation/SeatJigsaw.tsx
TSLint plugin has been replaced by new version of ESLint with TypeScript
support a long time ago.
> Remove TSLint plugin

- optaweb-employee-rostering-frontend/package-lock.json
- optaweb-employee-rostering-frontend/package.json
- optaweb-employee-rostering-frontend/src/ui/components/WeekPicker.test.tsx
- optaweb-employee-rostering-frontend/src/ui/components/WeekPicker.tsx
- optaweb-employee-rostering-frontend/src/ui/components/__snapshots__/WeekPicker.test.tsx.snap
"@wojtekmaj/react-daterange-picker" has a CSS issue causing it not to load properly at startup.
Replacing it with "react-datepicker" since we already use it in other components and it is more popular and maintained.
Fixes #463.
> Replace DatePicker component used in WeekPicker to prevent bad CSS styling (#463)

- optaweb-employee-rostering-frontend/cypress/integration/newTenantBasicWorkflow.js
For sake of stable tests, we need to pass valid data that would dynamically adjust
Early the schedule has been trying to plan for the past, since dates
in the test have been written in the stone. Currently, the date of shift planning is related
to the current date and the planning activity is set to the Wednesday of the next week
So 18th of September you will test schedule on the 23rd of September (18 -> next week -> Wed)
[PLANNER-2110](https://issues.redhat.com/browse/PLANNER-2110)
> Make planning items be in the future

- optaweb-employee-rostering-standalone/pom.xml
- pom.xml
In a multithreaded build, optaweb-employee-rostering-standalone
is sometimes built before optaweb-employee-rostering-frontend
has finished, causing the resource plugin to error when it
does not find optaweb-employee-rostering-frontend.zip
(only occurs when no version of it exists in .m2). Adding
optaweb-employee-rostering-frontend artifacts as dependencies
seem to fix it.
<details>
<summary>
</summary>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product …
> Fix error in multithreaded build caused by missing frontend zip

- optaweb-employee-rostering-standalone/pom.xml
- pom.xml
In a multithreaded build, optaweb-employee-rostering-standalone
is sometimes built before optaweb-employee-rostering-frontend
has finished, causing the resource plugin to error when it
does not find optaweb-employee-rostering-frontend.zip
(only occurs when no version of it exists in .m2). Adding
optaweb-employee-rostering-frontend artifacts as dependencies
seem to fix it.
(cherry picked from commit 1110d1fa33fd8b623a488cf9fd1a0a703cc99102)
<details>
<summary>
</summary>
* for a <b>full production …
> (7.x) Fix error in multithreaded build caused by missing frontend zip

- optaweb-employee-rostering-backend/pom.xml
- pom.xml
From 7.45 onward, mvel is decoupled from Drools,
so to compile a Drools file, we need to add
drools-mvel to our classpath
<details>
<summary>
</summary>
</details>
> Add drools-mvel to the classpath

- .github/workflows/pull_request.yml
- optaweb-employee-rostering-frontend/cypress.json
- optaweb-employee-rostering-frontend/cypress/integration/newTenantBasicWorkflow.js
- optaweb-employee-rostering-frontend/cypress/test_runners/nodeTestRunner.js
- optaweb-employee-rostering-frontend/cypress/tsconfig.json
- optaweb-employee-rostering-standalone/README.adoc
- optaweb-employee-rostering-standalone/pom.xml
[PLANNER-2188](https://issues.redhat.com/browse/PLANNER-2188)
Don't fail the build if there are some unstable/failed UI tests.
By default in case of test failure `cypress run` finishes with 1 ... n code (n - number of failing tests)
Then this result propagates to the podman and to the exec-maven-plugin and to the Jenkins
What we need is
If Cypress test failed then mark build successful && make reports => Jenkins will interpret this as unstable
If Cypress was unable to run tests || failed to execute || podman failed then mark build as failed => Jenkins will mark build as failed
I made a small wrapper for the tests so it is possible to: 
- manage exit code
- use more than one test
The test runner is nothing but wrapper to run tests in node to customize exit code
Alternatives:
- It is …
> Change exit code for cypress tests

- optaweb-employee-rostering-backend/pom.xml
- optaweb-employee-rostering-backend/src/test/java/org/optaweb/employeerostering/admin/AdminRestControllerTest.java
- optaweb-employee-rostering-backend/src/test/java/org/optaweb/employeerostering/contract/ContractRestControllerTest.java
- optaweb-employee-rostering-backend/src/test/java/org/optaweb/employeerostering/contract/ContractServiceTest.java
- optaweb-employee-rostering-backend/src/test/java/org/optaweb/employeerostering/employee/EmployeeRestControllerTest.java
- optaweb-employee-rostering-backend/src/test/java/org/optaweb/employeerostering/employee/EmployeeServiceTest.java
- optaweb-employee-rostering-backend/src/test/java/org/optaweb/employeerostering/exception/ExceptionDataMapperTest.java
- optaweb-employee-rostering-backend/src/test/java/org/optaweb/employeerostering/generator/RosterGeneratorTest.java
- optaweb-employee-rostering-backend/src/test/java/org/optaweb/employeerostering/roster/RosterRestControllerTest.java
- optaweb-employee-rostering-backend/src/test/java/org/optaweb/employeerostering/rotation/RotationRestControllerTest.java
- optaweb-employee-rostering-backend/src/test/java/org/optaweb/employeerostering/rotation/RotationServiceTest.java
- optaweb-employee-rostering-backend/src/test/java/org/optaweb/employeerostering/shift/ShiftRestControllerTest.java
- optaweb-employee-rostering-backend/src/test/java/org/optaweb/employeerostering/shift/ShiftServiceTest.java
- optaweb-employee-rostering-backend/src/test/java/org/optaweb/employeerostering/skill/SkillRestControllerTest.java
- optaweb-employee-rostering-backend/src/test/java/org/optaweb/employeerostering/skill/SkillServiceTest.java
- optaweb-employee-rostering-backend/src/test/java/org/optaweb/employeerostering/solver/AbstractSolverTest.java
- optaweb-employee-rostering-backend/src/test/java/org/optaweb/employeerostering/solver/ConstraintProviderSolverTest.java
- optaweb-employee-rostering-backend/src/test/java/org/optaweb/employeerostering/solver/DroolsSolverTest.java
- optaweb-employee-rostering-backend/src/test/java/org/optaweb/employeerostering/spot/SpotRestControllerTest.java
- optaweb-employee-rostering-backend/src/test/java/org/optaweb/employeerostering/spot/SpotServiceTest.java
- optaweb-employee-rostering-backend/src/test/java/org/optaweb/employeerostering/tenant/TenantRestControllerTest.java
- optaweb-employee-rostering-backend/src/test/java/org/optaweb/employeerostering/util/HierarchyTreeTest.java
- optaweb-employee-rostering-benchmark/pom.xml
- optaweb-employee-rostering-benchmark/src/test/java/org/optaweb/employeerostering/BenchmarkTest.java
https://issues.redhat.com/browse/PLANNER-2102
<details>
<summary>
</summary>
</details>
> PLANNER-2102: Migrate OptaWeb Employee Rostering to JUnit 5

- optaweb-employee-rostering-backend/src/test/java/org/optaweb/employeerostering/contract/ContractServiceTest.java
- optaweb-employee-rostering-backend/src/test/java/org/optaweb/employeerostering/employee/EmployeeServiceTest.java
- optaweb-employee-rostering-backend/src/test/java/org/optaweb/employeerostering/exception/ExceptionDataMapperTest.java
- optaweb-employee-rostering-backend/src/test/java/org/optaweb/employeerostering/roster/RosterRestControllerTest.java
- optaweb-employee-rostering-backend/src/test/java/org/optaweb/employeerostering/solver/AbstractSolverTest.java
- optaweb-employee-rostering-backend/src/test/java/org/optaweb/employeerostering/util/HierarchyTreeTest.java
- optaweb-employee-rostering-benchmark/src/test/java/org/optaweb/employeerostering/BenchmarkTest.java
https://issues.redhat.com/browse/PLANNER-2103
<details>
<summary>
</summary>
</details>
> PLANNER-2103: Replace all JUnit Assertions with AssertJ

- .github/workflows/pull_request.yml
https://issues.redhat.com/browse/BXMSPROD-1062
related PRs:
* https://github.com/kiegroup/kie-soup/pull/164
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/483
* https://github.com/kiegroup/drools/pull/3216
* https://github.com/kiegroup/optaplanner/pull/1013
* https://github.com/kiegroup/jbpm/pull/1795
* https://github.com/kiegroup/kie-jpmml-integration/pull/47
* https://github.com/kiegroup/droolsjbpm-integration/pull/2309
* https://github.com/kiegroup/openshift-drools-hacep/pull/104
* https://github.com/kiegroup/droolsjbpm-tools/pull/123
* https://github.com/kiegroup/lienzo-core/pull/139
* https://github.com/kiegroup/lienzo-tests/pull/112
* https://github.com/kiegroup/appformer/pull/1074
* https://github.com/kiegroup/kie-uberfire-extensions/pull/110
* …
> BXMSPROD-1062 kiegroup/github-action-build-chain updated

- .github/workflows/pull_request.yml
https://issues.redhat.com/browse/BXMSPROD-1062
related PRs:
* https://github.com/kiegroup/kie-soup/pull/164
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/483
* https://github.com/kiegroup/drools/pull/3216
* https://github.com/kiegroup/optaplanner/pull/1013
* https://github.com/kiegroup/jbpm/pull/1795
* https://github.com/kiegroup/kie-jpmml-integration/pull/47
* https://github.com/kiegroup/droolsjbpm-integration/pull/2309
* https://github.com/kiegroup/openshift-drools-hacep/pull/104
* https://github.com/kiegroup/droolsjbpm-tools/pull/123
* https://github.com/kiegroup/lienzo-core/pull/139
* https://github.com/kiegroup/lienzo-tests/pull/112
* https://github.com/kiegroup/appformer/pull/1074
* https://github.com/kiegroup/kie-uberfire-extensions/pull/110
* …
> [master] BXMSPROD-1062 kiegroup/github-action-build-chain updated

- optaweb-employee-rostering-backend/pom.xml
Swagger UI was accidentally removed in
593b640f5ff230c4cd2c9aa90190d102cd1d9b38
<details>
<summary>
</summary>
</details>
> Readd Swagger UI

- optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/domain/rotation/TimeBucket.java
Using `@OneToMany` adds an additional constraint of no two time buckets
sharing any additional skills, which is unwarranted. The relation
should be `@ManyToMany` instead.
Fixes #541.
<details>
<summary>
</summary>
</details>
> Use @ManyToMany instead of @OneToMany in TimeBucket additionalSkillSet

- optaweb-employee-rostering-backend/pom.xml
The validation starter was a dependency of the web starter but it was
removed in Spring Boot 2.3.0.
The KIE parent is going to upgrade to Spring Boot 2.4.3 or higher soon.
Adding the validation starter dependency will prevent build failure in
the future.
<details>
<summary>
</summary>
</details>
> Add spring-boot-starter-validation

- optaweb-employee-rostering-backend/pom.xml
- junit-vintage-engine:5.5.2 currently provided by Spring Boot Starter
Test is not compatible with JUnit 4.13.1.
- We can afford the downgrade because the security problem fixed in
4.13.1 doesn't affect this project. See
https://github.com/junit-team/junit4/blob/HEAD/doc/ReleaseNotes4.13.1.md
<details>
<summary>
</summary>
* for an <b>upstream build</b> please add comment: <b>Jenkins run …
> Downgrade JUnit 4 to 4.13

- optaweb-employee-rostering-backend/pom.xml
- optaweb-employee-rostering-standalone/pom.xml
- pom.xml
Fixes up two previous PRs:
- #555: Applies the JUnit downgrade to the benchmark module as well.
- #556: Fixes the standalone module, where validation API became excluded when the Spring Boot upgrade was reverted (https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1579).
The incompleteness of #555 is my mistake. I forgot there are two Java modules in this project (backend, benchmark) and no test being executed is difficult to spot (obviously) because there is no failure.
Context: The issue of no tests being executed existed since Oct 26 2020 (https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1500). This is nobody's fault. There was zero chance of discovering this other than by accident because
1. we no longer work on the 7.x branch regularly, and
2. `master` doesn't use …
> Fixup junit and validation

- .github/workflows/pull_request.yml
JIRA
https://issues.redhat.com/browse/BXMSPROD-1214
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1595
https://github.com/kiegroup/kie-soup/pull/182
https://github.com/kiegroup/droolsjbpm-knowledge/pull/504
https://github.com/kiegroup/drools/pull/3406
https://github.com/kiegroup/optaplanner/pull/1177
https://github.com/kiegroup/lienzo-core/pull/141
https://github.com/kiegroup/lienzo-tests/pull/113
https://github.com/kiegroup/appformer/pull/1110
https://github.com/kiegroup/kie-uberfire-extensions/pull/111
https://github.com/kiegroup/jbpm/pull/1875
https://github.com/kiegroup/kie-jpmml-integration/pull/49
https://github.com/kiegroup/droolsjbpm-integration/pull/2405
https://github.com/kiegroup/kie-wb-playground/pull/103
https://github.com/kiegroup/kie-wb-common/pull/3579 …
> BXMSPROD-1214 Install takari error workaround (master)

- .github/workflows/pull_request.yml
- .mvn/extensions.xml
https://issues.redhat.com/browse/BXMSPROD-1228
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/441
<details>
<summary>
</summary>
</details>
> [8.3.x] BXMSPROD-1228: Add Takari extension to fix GitHub Actions

- .github/workflows/pull_request.yml
The config URL with the `${BRANCH}` works on master but will break
every time an 8.x release branch is created because there is no matching
8.x branch in droolsjbpm-build-bootstrap.
All OptaWeb 8.x branches in the near future should depend on the
master branch in droolsjbpm-build-bootstrap.
<details>
<summary>
</summary> …
> Avoid future problems with pull request workflow config URL

- optaweb-employee-rostering-standalone/pom.xml
I need to run docker with non-root so to be able to delete files generated inside the container.
Though for podman it is opposite - if you run it as a non-root it is unable to write to the binded volume
I used here 1000:1000 as user and group id since it is a default non-root. So it exist both in container and on host so to not get noisy notifications like:
"groups: cannot find name for group ID"
"I have no name!"
- your container, complaining
That is required for setting up optawebs in the pipeline. So here I made a short version of the pipeline which is also require to be able to remove cypress reports generated in docker
https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/adupliak/job/quickstarts-release-pipeline/job/optaplanner-deploy/83/
Pay attention to the owner it …
> Configure docker to run as non-root user

- optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/service/solver/EmployeeRosteringConstraintProvider.java
- optaweb-employee-rostering-backend/src/test/java/org/optaweb/employeerostering/solver/AbstractSolverTest.java
- optaweb-employee-rostering-backend/src/test/java/org/optaweb/employeerostering/solver/DroolsSolverTest.java
There was a difference between scoreDrl and constraint stream
implementations that was not tested in tests. Namely, when
the rotation employee is null and the employee is not null.
The CS impl triggers a penalty, whereas the DRL does not
trigger a penalty. The DRL behavior is the correct one.
As a result of switching to CS by default, this triggers
a NPE on frontend since it creates a employeeNotRotationEmployee
violation with a null rotation employee (which the frontend
assume must not be null).
This adds a test and make CS behave the same as DRL
<details>
<summary>
</summary>
* …
> Make "employeeNotRotationEmployee" not trigger if shift.getRotationEmployee() is null

- .github/workflows/pull_request.yml
Replicates kiegroup/optaweb-vehicle-routing/pull/474 to make the two optaweb repos consistent and to fix the problem with removing `heroku` package that is not available.
<details>
<summary>
</summary>
</details>
> Fix GitHub Actions

- runLocally.sh
This allows for example to change HTTP port: `./runLocally.sh spain -Dquarkus.http.port=9090`.
<details>
<summary>
</summary>
</details>
> Pass extra arguments from runLocally.sh to java

- pom.xml
https://issues.redhat.com/browse/PLANNER-2389
https://github.com/kiegroup/optaplanner/pull/1254
https://github.com/kiegroup/optaplanner-quickstarts/pull/93
https://github.com/kiegroup/optaweb-employee-rostering/pull/602
https://github.com/kiegroup/optaweb-vehicle-routing/pull/471
<details>
<summary>
</summary>
</details>
> PLANNER-2389 Upgrade Quarkus to 1.13

- Dockerfile
- optaweb-employee-rostering-backend/Dockerfile
- optaweb-employee-rostering-standalone/Dockerfile
Drools requires a JDK unless an additional dependency is used. Tested locally on Podman. (The error happens on master w/ Podman, and doesn't happen with this commit on Podman)
https://issues.redhat.com/browse/RHDM-1737
<details>
<summary>
</summary>
</details>
> RHDM-1737: Use JDK base image so Drools can find a compiler

- Dockerfile
- optaweb-employee-rostering-backend/Dockerfile
- optaweb-employee-rostering-standalone/Dockerfile
https://issues.redhat.com/browse/RHDM-1737
<details>
<summary>
</summary>
</details>
> (8.5.x) RHDM-1737: Use JDK base image so Drools can find a compiler

- .github/workflows/pull_request.yml
https://issues.redhat.com/browse/BXMSPROD-1363
- https://github.com/kiegroup/optaweb-employee-rostering/pull/639
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/514
<details>
<summary>
</summary>
</details>
> BXMSPROD-1363 [master] build-chain definition and project-dependencies upgraded to v2.1

- optaweb-employee-rostering-backend/pom.xml
See https://stackoverflow.com/questions/50237516/proper-fix-for-java-10-complaining-about-illegal-reflection-access-by-jaxb-impl
https://issues.redhat.com/browse/PLANNER-2390
<details>
<summary>
</summary>
</details>
> PLANNER-2390: Replace old jaxb xml impl with Java 16 compliant one

- .github/workflows/ci.yml
Follows up on #647.
The CI matrix should contain the [latest Java release](https://www.oracle.com/java/technologies/java-se-support-roadmap.html) (now 16).
<details>
<summary>
</summary>
</details>
> Update CI matrix to Java 16

- .github/workflows/pull_request.yml
The build chain tool is not properly taken into account for excluded projects. https://github.com/kiegroup/github-action-build-chain/pull/160 solves the problem
related PR
- https://github.com/kiegroup/github-action-build-chain/pull/160
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/527
- https://github.com/kiegroup/optaweb-employee-rostering/pull/654
- https://github.com/kiegroup/optaplanner/pull/1418
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/528
- https://github.com/kiegroup/optaweb-employee-rostering/pull/655
<details>
<summary>
</summary>
* for a …
> BXMSPROD-1413 [master] [build-chain upgrade] exclude projects not taken into account

- .github/workflows/pull_request.yml
The build chain tool is not properly taken into account for excluded projects. https://github.com/kiegroup/github-action-build-chain/pull/160 solves the problem
related PR
- https://github.com/kiegroup/github-action-build-chain/pull/160
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/527
- https://github.com/kiegroup/optaweb-employee-rostering/pull/654
- https://github.com/kiegroup/optaplanner/pull/1418
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/528
- https://github.com/kiegroup/optaweb-employee-rostering/pull/655
<details>
<summary>
</summary>
* for a …
> BXMSPROD-1413 [7.x] [build-chain upgrade] exclude projects not taken into account

- optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/domain/shift/Shift.java
- optaweb-employee-rostering-backend/src/main/resources/application.properties
This reverts commit 7f0668848fafe9a20f858c91eb0107b7c839e62c.
Tested locally; can confirm solving works now w/o this workaround.
<details>
<summary>
</summary>
</details>
> Revert "PLANNER-2504 remove final modifier (workaround)"

- .github/workflows/ci.yml
The CI jobs (from the CI matrix workflow) also fail occasionally. We need the Cypress test video and logs etc. to analyze the issue.
<details>
<summary>
</summary>
</details>
> Upload artifacts in the CI workflow

- .github/workflows/pull_request.yml
**Thank you for submitting this pull request**
**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1475
**referenced Pull Requests**: 
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1770
* https://github.com/kiegroup/kie-soup/pull/228
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/549
* https://github.com/kiegroup/drools/pull/3835
* https://github.com/kiegroup/optaplanner/pull/1577
* https://github.com/kiegroup/lienzo-core/pull/152
* https://github.com/kiegroup/lienzo-tests/pull/126
* https://github.com/kiegroup/appformer/pull/1197
* https://github.com/kiegroup/kie-uberfire-extensions/pull/124
* https://github.com/kiegroup/jbpm/pull/2024
* https://github.com/kiegroup/kie-jpmml-integration/pull/65
* https://github.com/kiegroup/droolsjbpm-integration/pull/2607
* …
> [main] BXMSPROD-1475 force maven to 3.8.1

- .github/workflows/ci.yml
- .github/workflows/pull_request.yml
https://issues.redhat.com/browse/BXMSPROD-1475
Related PRs:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1774
* https://github.com/kiegroup/kie-soup/pull/229
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/551
* https://github.com/kiegroup/drools/pull/3837
* https://github.com/kiegroup/optaplanner/pull/1579
* https://github.com/kiegroup/lienzo-core/pull/153
* https://github.com/kiegroup/lienzo-tests/pull/127
* https://github.com/kiegroup/appformer/pull/1198
* https://github.com/kiegroup/kie-uberfire-extensions/pull/125
* https://github.com/kiegroup/jbpm/pull/2027
* https://github.com/kiegroup/kie-jpmml-integration/pull/66
* https://github.com/kiegroup/droolsjbpm-integration/pull/2608
* https://github.com/kiegroup/kie-wb-playground/pull/120
* …
> [7.59.x][BXMSPROD-1475] GHA maven version

- optaweb-employee-rostering-frontend/src/ui/components/calendar/EventWrapper.tsx
- optaweb-employee-rostering-frontend/src/ui/components/calendar/ReactBigCalendarOverrides.css
- optaweb-employee-rostering-frontend/src/ui/components/calendar/__snapshots__/EventWrapper.test.tsx.snap
- optaweb-employee-rostering-frontend/src/ui/components/calendar/__snapshots__/Schedule.test.tsx.snap
Closes #691
<details>
<summary>
</summary>
* for a <b>specific pull request build</b> please add comment: <b>Jenkins (re)run [optaweb-employee-rostering] tests</b>
* for a <b>Quarkus LTS check</b> please add comment: <b>Jenkins run LTS</b>
* for a <b>specific Quarkus LTS check</b> please add comment: <b>Jenkins (re)run …
> Fix some shifts not being editable due to data-popper-reference-hidden=true

- optaweb-employee-rostering-backend/src/main/resources/application.properties
Missing DELETE method makes it impossible to delete shifts in dev mode.
The allowed origin makes it difficult to use the front end dev server on
a different port than 3000.
All this CORS fine-tuning is redundant in dev mode.
<details>
<summary>
</summary>
* for a <b>specific pull request build</b> please add comment: <b>Jenkins (re)run [optaweb-employee-rostering] tests</b>
* for an <b>upstream …
> Remove needless CORS restrictions

- .github/workflows/sonarcloud.yml
Copy-pasted from https://github.com/kiegroup/optaplanner/blob/fb2395c33ed9d6b63954e2a040429e494f835926/.github/workflows/sonarcloud.yml with some minor cleanup:
```diff
1,2c1,2
< # Runs the SonarCloud analysis of the optaplanner main branch after a PR is merged.
< name: OptaPlanner SonarCloud Analysis
---
> # Runs SonarCloud analysis of the main branch after a PR is merged.
> name: SonarCloud analysis
9a10
>       - 'CODEOWNERS'
10a12
>       - '.gitattributes'
13,14c15,18
<       - '*.txt'
<       - '.ci/**'      
---
>       - '**.txt'
>       - 'runOnOpenShift.sh'
>       - 'runLocally.sh'
>       - '.ci/**'
49c53
<         run: mvn -B --fail-at-end validate -Psonarcloud-analysis -Dsonar.projectKey=org.optaplanner:optaplanner -Dsonar.login=${{ env.SONARCLOUD_TOKEN }}
---
>         run: …
```
> PLANNER-2465: Run SonarCloud analysis after push to main

- optaweb-employee-rostering-backend/pom.xml
- optaweb-employee-rostering-benchmark/pom.xml
- pom.xml
https://issues.redhat.com/browse/RHPAM-4111
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1872
- https://github.com/kiegroup/droolsjbpm-integration/pull/2693
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/641
- https://github.com/kiegroup/optaweb-employee-rostering/pull/755
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for …
> [7.x] RHPAM-4111: Update dependencies to match Spring Boot 2.4.9

- .ci/jenkins/dsl/jobs.groovy
- .github/workflows/full-downstream.yml
- .github/workflows/pull_request.yml
- .github/workflows/sonarcloud.yml
Depends on https://github.com/kiegroup/kogito-pipelines/pull/388
I backported changes from `main` which are useful and removed drools references.
- https://github.com/kiegroup/kogito-pipelines/pull/388
- https://github.com/kiegroup/kogito-pipelines/pull/390
- https://github.com/kiegroup/kogito-runtimes/pull/2028
- https://github.com/kiegroup/optaplanner/pull/1850
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/662
- https://github.com/kiegroup/optaweb-employee-rostering/pull/771
- https://github.com/kiegroup/optaplanner-quickstarts/pull/295
- https://github.com/kiegroup/kogito-apps/pull/1258
- https://github.com/kiegroup/kogito-examples/pull/1144
- https://github.com/kiegroup/kogito-images/pull/1126
- https://github.com/kiegroup/kogito-operator/pull/1139
> [1.13.x] Prepare branch for productization

- optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/service/common/IndictmentUtils.java
- optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/service/roster/RosterService.java
- optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/service/shift/ShiftService.java
- optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/service/solver/EmployeeRosteringConstraintProvider.java
Fixes #776
Due to how justification lists in Constraint Stream works, Shift
indictments never included contract violation constraint matches
(since the shift is not in their justification list because the shifts
were removed in a groupBy operation).
Because the justification list still have the employee, we can use
the indictment of the employee to gets its contract violation constraint
matches, and add them to the shift's constraint matches.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain …
> Fix issue #776: Link contract violation constraint matches from employee to shift

- optaweb-employee-rostering-frontend/package-lock.json
- optaweb-employee-rostering-frontend/package.json
Fixes #753. `node-sass` is now deprecated, and it recommended to use `sass` instead: https://www.npmjs.com/package/node-sass
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions …
> Replace node-sass with sass

- .github/pull_request_template.md
* https://github.com/kiegroup/optaplanner/pull/1889
* https://github.com/kiegroup/optaplanner-quickstarts/pull/312
* https://github.com/kiegroup/optaweb-employee-rostering/pull/781
* https://github.com/kiegroup/optaweb-vehicle-routing/pull/668
<details>
<summary>
</summary>
[build-chain …
> CI status webpage

- .github/workflows/pull_request.yml
Signed-off-by: Lukáš Petrovický <lpetrovi@redhat.com>
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple …
> Enable JDK 18 on Pull Requests

- pom.xml
<details>
<summary>
</summary> …
> io.springfox removed

- optaweb-employee-rostering-backend/pom.xml
- pom.xml
`jakarta.*` JARs contain the same APIs as the old `javax.*` JARs. Jakarta is
already used and managed by Quarkus. So this change just removes
duplicate JARs.
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line …
> Use Jakarta APIs

- build/release/upload_distribution.sh
Updates the upload server for docs and distribution.
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple …
> [8.20.x] Update the upload server

- build/release/upload_distribution.sh
Updates the upload server for docs and distribution.
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple …
> Update the upload server

- README.adoc
Linking OptaPlanner instructions
Removed sonar gate badge + added similar from OptaPlanner parent badges
https://issues.redhat.com/browse/PLANNER-2684
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in …
> Update code formater + badges

- optaweb-employee-rostering-frontend/cypress/integration/newTenantBasicWorkflow.js
- optaweb-employee-rostering-frontend/src/ui/components/WeekPicker.css
To avoid element squeezing to the calendar due to small display settings I have added width attribute
+ To be able repeatedly test the app - made tenant name unique
https://qe-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/TESTING/job/7.13/job/KOGITO_RUNTIMES-CR/job/community/job/baseline/job/optaweb-employee-rostering-openshift-baseline/3/artifact/run-tests-with-build-project-sources-dependency-get/target/sources/optaweb-employee-rostering-8.13.0.Final-redhat-00003/optaweb-employee-rostering-frontend/cypress/screenshots/newTenantBasicWorkflow.js/basic-tenant-workflow%20(failed).png
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories …
> Add width to the calendar element + make tenant name unique

- pom.xml
* https://github.com/kiegroup/optaweb-employee-rostering/pull/815
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1963
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions …
> [7.x] Spring dependencies moved to parent module

- .github/workflows/pull_request.yml
<details>
<summary>
</summary> …
> Add a check that fails if there are any uncommitted changes

- .ci/jenkins/dsl/Jenkinsfile.seed
https://issues.redhat.com/browse/KOGITO-7356
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/484
- https://github.com/kiegroup/drools/pull/4446
- https://github.com/kiegroup/kogito-runtimes/pull/2252
- https://github.com/kiegroup/kogito-apps/pull/1375
- https://github.com/kiegroup/kogito-examples/pull/1285
- https://github.com/kiegroup/kogito-images/pull/1275
- https://github.com/kiegroup/kogito-operator/pull/1204
- https://github.com/kiegroup/optaplanner/pull/2023
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/708
- https://github.com/kiegroup/optaweb-employee-rostering/pull/826
- https://github.com/kiegroup/optaplanner-quickstarts/pull/352
> [8.13.x] KOGITO-7356 Do not use master node in pipelines

- .ci/jenkins/dsl/test.sh
- .github/workflows/jenkins-tests-PR.yml
<details>
<summary>
</summary> …
> [PLANNER-2728] Extract optaplanner release from Kogito

- optaweb-employee-rostering-frontend/package-lock.json
**Thank you for submitting this pull request**
**JIRA**:
- https://issues.redhat.com/browse/RHPAM-4271
**referenced Pull Requests**: 
- https://github.com/kiegroup/appformer/pull/1304
- https://github.com/kiegroup/kie-wb-common/pull/3778
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/753
- https://github.com/kiegroup/optaweb-employee-rostering/pull/854
- https://github.com/kiegroup/kogito-apps/pull/1461
Upgrade `minimist` package to version `1.2.6`.
**NB**: No need to fix this in `main` branch since it is already fixed.
> [7.67.x] [RHPAM-4271] CVE-2021-44906: Upgrade minimist to 1.2.6

- optaweb-employee-rostering-frontend/package-lock.json
- optaweb-employee-rostering-frontend/package.json
https://issues.redhat.com/browse/RHPAM-4530
related PRs:
* https://github.com/kiegroup/optaweb-employee-rostering/pull/855
* https://github.com/kiegroup/optaweb-employee-rostering/pull/856
* https://github.com/kiegroup/optaweb-employee-rostering/pull/857
> [7.67.x] RHPAM-4530 lock-treatment-tool upgraded to 0.2.1 CVE-2021-23383
