kiegroup/optaweb-employee-rostering

README.adoc, openshift/templates/optashift-employee-rostering-template-binary.yaml, openshift/templates/optashift-employee-rostering-template.yaml, pom.xml, provision.sh
Initial implementation of the OpenShift template. Still needs some finetuning. Also misses Route configuration (which we'll add later).
=> Openshift template

optashift-employee-rostering-shared/src/main/java/org/optaplanner/openshift/employeerostering/shared/jackson/LocalDateDeserializer.java, optashift-employee-rostering-shared/src/main/java/org/optaplanner/openshift/employeerostering/shared/jackson/LocalDateSerializer.java, optashift-employee-rostering-shared/src/main/java/org/optaplanner/openshift/employeerostering/shared/jackson/LocalDateTimeDeserializer.java, optashift-employee-rostering-shared/src/main/java/org/optaplanner/openshift/employeerostering/shared/jackson/LocalDateTimeSerializer.java, optashift-employee-rostering-shared/src/main/java/org/optaplanner/openshift/employeerostering/shared/roster/view/AbstractRosterView.java, optashift-employee-rostering-shared/src/main/java/org/optaplanner/openshift/employeerostering/shared/timeslot/TimeSlot.java
@ge0ffrey This works with Wildfly 10.0.0.Final. I haven't tested on EAP 7 yet; should I test it on EAP 7.1.0 Beta or EAP 7.0.0?
=> PLANNER-903: Made all Serializers/Deserializers internal to fix conflicts from different versions

optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/calendar/Calendar.java, optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/calendar/ShiftDrawable.java, optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/calendar/twodayview/TwoDayView.java, optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/calendar/twodayview/TwoDayViewPresenter.java, optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/calendar/twodayview/TwoDayViewState.java, optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/employee/EmployeeDrawable.java, optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/spot/SpotDrawable.java, optashift-employee-rostering-gwtui/src/main/resources/org/optaplanner/openshift/employeerostering/gwtui/client/resources/css/calendar.css
-Added Padding to column headers
-Fixed position of time slot inner text
-Fixed Calendar start date being wrong on startup
-Changed font to "Sans-Serif"
=> PLANNER-940: UI tweaks and fixes

README.adoc
Documenting the Code Formatter and updating IntelliJ configuration steps.
=> README update

optashift-employee-rostering-distribution/src/main/assembly/filtered-resources/ReadMeOptaShiftEmployeeRostering.txt
When I was verifying the [RHDM-364](https://issues.jboss.org/browse/RHDM-364) issue, I noticed that the available README file in the product is not very detailed and "neat", so I decided to update it a little bit.
@ge0ffrey, could you please let me know what you think?
=> Update the ReadMeOptaShiftEmployeeRostering.txt file.

optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/OptaShiftRosteringEntryPoint.java
=> PLANNER-1031: Log error messages to javascript logger before showing

optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/common/KiePager.java, optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/spot/SpotListPanel.java, optashift-employee-rostering-gwtui/src/main/resources/org/optaplanner/openshift/employeerostering/gwtui/client/spot/SpotListPanel.html
This commit is https://github.com/kiegroup/optashift-employee-rostering/commit/c868836834061a918b4897b47000b4ec6561babc, it appears to got reverted for some reason during an auto merge.
=> Added a a missing commit

optashift-employee-rostering-shared/src/main/java/org/optaplanner/openshift/employeerostering/shared/employee/EmployeeRestService.java, optashift-employee-rostering-shared/src/main/java/org/optaplanner/openshift/employeerostering/shared/shift/ShiftRestService.java, optashift-employee-rostering-shared/src/main/java/org/optaplanner/openshift/employeerostering/shared/skill/SkillRestService.java, optashift-employee-rostering-shared/src/main/java/org/optaplanner/openshift/employeerostering/shared/spot/SpotRestService.java
This fixes delete on entities not used, but not archiving entities that are used
=> PLANNER-1060: Removed regex since GWT has no idea how to handle it

openshift/templates/optashift-employee-rostering-template-binary.yaml, openshift/templates/optashift-employee-rostering-template.yaml, provision.sh
- Prefer running the script with #!/bin/bash instead of #!/bin/sh so it finds "oc" and "mvn" more easily (if they are declared in .bashrc)
- remove old github url references
- remove "demo" and straighten out naming
=> provision.sh improvements

pom.xml
https://issues.jboss.org/browse/RHDM-518
=> RHDM-518: syncing Errai version property

optashift-employee-rostering-gwtui/src/main/java/org/optaplanner/openshift/employeerostering/gwtui/client/pages/rotation/RotationPage.java, optashift-employee-rostering-gwtui/src/main/resources/org/optaplanner/openshift/employeerostering/gwtui/client/app/AppView.less, optashift-employee-rostering-gwtui/src/main/resources/org/optaplanner/openshift/employeerostering/gwtui/client/header/HeaderView.html, optashift-employee-rostering-gwtui/src/main/resources/org/optaplanner/openshift/employeerostering/gwtui/client/pages/employeeroster/EmployeeRosterPage.html, optashift-employee-rostering-gwtui/src/main/resources/org/optaplanner/openshift/employeerostering/gwtui/client/pages/rotation/RotationPage.html, optashift-employee-rostering-gwtui/src/main/resources/org/optaplanner/openshift/employeerostering/gwtui/client/pages/spotroster/SpotRosterPage.html, optashift-employee-rostering-gwtui/src/main/resources/org/optaplanner/openshift/employeerostering/gwtui/public/roster.less
Fixes Selection_720.png and Selection_722.png of https://issues.jboss.org/browse/PLANNER-1097
=> Fixed styling of headers

openshift/templates/optashift-employee-rostering-template-binary.yaml, provision.sh
* Reduce verbosity
* Improve order of attributes (input before strategy before output)
* Increase resource limits so it works on OpenShift Dedicated
=> OpenShift template clean up

optashift-employee-rostering-gwtui/src/main/resources/org/optaplanner/openshift/employeerostering/gwtui/client/app/AppView.less, optashift-employee-rostering-gwtui/src/main/resources/org/optaplanner/openshift/employeerostering/gwtui/public/kie.less
Fixes margin and border-collapse on Firefox
=> PLANNER-1097: Fixed CSS styling issues

optashift-employee-rostering-server/pom.xml, optashift-employee-rostering-server/src/main/java/org/optaplanner/openshift/employeerostering/server/roster/RosterGenerator.java, optashift-employee-rostering-server/src/main/java/org/optaplanner/openshift/employeerostering/server/solver/WannabeSolverManager.java, optashift-employee-rostering-server/src/test/java/org/optaplanner/openshift/employeerostering/server/solver/SolverTest.java, optashift-employee-rostering-server/src/test/resources/logback-test.xml, optashift-employee-rostering-shared/pom.xml, optashift-employee-rostering-webapp/pom.xml, pom.xml
Currently this test fails, but once Christopher's DRL fix is in, I 'll ask jenkins to retest this.
=> Add a simple SolverTest to smoke test the DRL, solver configuration, etc

employee-rostering-server/src/main/java/org/optaweb/employeerostering/server/shift/ShiftRestServiceImpl.java
Fixes #175. The updateRotation method may be removed to match single entity CRUD operation of other entities (Employee, Spot, Shift, etc.) instead of batch (slightly related to https://issues.jboss.org/browse/PLANNER-1224).
=> PLANNER-1240: Fixed bug in updateRotation which discarded rotation employee in ShiftTemplate

employee-rostering-shared/src/main/java/org/optaweb/employeerostering/shared/employee/Employee.java, employee-rostering-shared/src/main/java/org/optaweb/employeerostering/shared/spot/Spot.java
This change removes warnings when using ProgresSQL on Wildfly
=> PLANNER-1220: Added @JoinTable to Spot and Employe Many-to-Many relations

employee-rostering-docs/src/main/asciidoc/Introduction/SystemProperties/SystemProperties-section.adoc, employee-rostering-server/src/main/filtered-resources/META-INF/persistence.xml, pom.xml
=> PLANNER-1278 expose system property org.optaweb.employeerostering.persistence.hbm2ddl.auto

employee-rostering-gwtui/pom.xml, employee-rostering-gwtui/src/main/java/org/optaweb/employeerostering/gwtui/client/common/BootstrapDateTimePicker.java, employee-rostering-gwtui/src/main/java/org/optaweb/employeerostering/gwtui/client/common/JQuery.java, employee-rostering-gwtui/src/main/java/org/optaweb/employeerostering/gwtui/client/common/LocalDatePicker.java, employee-rostering-gwtui/src/main/java/org/optaweb/employeerostering/gwtui/client/common/LocalDateTimePicker.java, employee-rostering-gwtui/src/main/java/org/optaweb/employeerostering/gwtui/client/common/LocalWeekDatePicker.java, employee-rostering-gwtui/src/main/java/org/optaweb/employeerostering/gwtui/client/common/MomentJs.java, employee-rostering-gwtui/src/main/java/org/optaweb/employeerostering/gwtui/client/pages/availabilityroster/AvailabilityRosterPageViewportBuilder.java, employee-rostering-gwtui/src/main/java/org/optaweb/employeerostering/gwtui/client/pages/shiftroster/ShiftRosterPageViewportBuilder.java, employee-rostering-gwtui/src/main/java/org/optaweb/employeerostering/gwtui/client/tenant/NewTenantForm.java, employee-rostering-gwtui/src/main/java/org/optaweb/employeerostering/gwtui/client/util/DateTimeUtils.java, employee-rostering-gwtui/src/main/resources/org/optaweb/employeerostering/gwtui/client/common/LocalDatePicker.html, employee-rostering-gwtui/src/main/resources/org/optaweb/employeerostering/gwtui/client/common/LocalDateTimePicker.css, employee-rostering-gwtui/src/main/resources/org/optaweb/employeerostering/gwtui/client/common/LocalDateTimePicker.html, employee-rostering-gwtui/src/main/resources/org/optaweb/employeerostering/gwtui/client/common/LocalWeekDatePicker.css, employee-rostering-gwtui/src/main/resources/org/optaweb/employeerostering/gwtui/client/common/LocalWeekDatePicker.html, employee-rostering-gwtui/src/main/resources/org/optaweb/employeerostering/gwtui/client/pages/shiftroster/ShiftEditForm.html, employee-rostering-gwtui/src/main/resources/org/optaweb/employeerostering/gwtui/public/gwtui.html, pom.xml
Added two dependencies that are required to use the one Patternfly uses:
- MomentJS (https://momentjs.com/), uses MIT license
- BootscrapDateTimePicker (https://eonasdan.github.io/bootstrap-datetimepicker/), uses MIT license
(https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/LICENSE) (for some reason they didn't put license info on the main website, but this is the date time picker Patternfly uses)
=> PLANNER-1230: Use Bootstrap based week-picker, date-picker, date-time-picker

pom.xml
(cherry picked from commit f93aadc959b3c4f70ef0eecda52cfaec2b3562fb)
=> upgraded version com.fasterxml.jackson to align to EAP 7.2.

employee-rostering-server/src/main/filtered-resources/META-INF/persistence.xml, employee-rostering-server/src/main/resources/META-INF/beans.xml, employee-rostering-webapp/pom.xml, employee-rostering-webapp/src/main/webapp/WEB-INF/beans.xml, pom.xml
=> PLANNER-1341 Upgrade to wildfly 14 (urgent blocker!)

employee-rostering-benchmark/pom.xml, employee-rostering-gwtui/pom.xml, employee-rostering-gwtui/src/main/module.gwt.xml, employee-rostering-restclient/pom.xml, employee-rostering-server/pom.xml, employee-rostering-shared/pom.xml, employee-rostering-webapp/pom.xml, pom.xml
https://issues.jboss.org/browse/PLANNER-1353 and https://issues.jboss.org/browse/PLANNER-1342
Switched parent to kie-parent and fixed all issues with that related change:
- enforcer violations
- GWT compilation
=> PLANNER-1353 switch from jboss-parent to kie-parent

employee-rostering-gwtui/src/main/java/org/optaweb/employeerostering/gwtui/client/pages/availabilityroster/AvailabilityRosterPageViewportBuilder.java, employee-rostering-gwtui/src/main/java/org/optaweb/employeerostering/gwtui/client/pages/rotation/RotationPageViewport.java, employee-rostering-gwtui/src/main/java/org/optaweb/employeerostering/gwtui/client/pages/rotation/RotationPageViewportBuilder.java, employee-rostering-gwtui/src/main/java/org/optaweb/employeerostering/gwtui/client/pages/rotation/RotationToolbar.java, employee-rostering-gwtui/src/main/java/org/optaweb/employeerostering/gwtui/client/pages/rotation/ShiftTemplateGridObject.java, employee-rostering-gwtui/src/main/java/org/optaweb/employeerostering/gwtui/client/pages/shiftroster/ShiftGridObject.java, employee-rostering-gwtui/src/main/java/org/optaweb/employeerostering/gwtui/client/pages/shiftroster/ShiftRosterPageViewportBuilder.java, employee-rostering-gwtui/src/main/java/org/optaweb/employeerostering/gwtui/client/viewport/DateTimeViewport.java, employee-rostering-gwtui/src/main/resources/org/optaweb/employeerostering/gwtui/client/pages/rotation/RotationToolbar.html, employee-rostering-restclient/src/main/java/org/optaweb/employeerostering/restclient/ServiceClientFactory.java, employee-rostering-server/src/main/java/org/optaweb/employeerostering/server/employee/EmployeeRestServiceImpl.java, employee-rostering-server/src/main/java/org/optaweb/employeerostering/server/rotation/RotationRestServiceImpl.java, employee-rostering-server/src/main/java/org/optaweb/employeerostering/server/shift/ShiftRestServiceImpl.java, employee-rostering-server/src/main/java/org/optaweb/employeerostering/server/skill/SkillRestServiceImpl.java, employee-rostering-shared/src/main/java/org/optaweb/employeerostering/shared/rotation/RotationRestService.java, employee-rostering-shared/src/main/java/org/optaweb/employeerostering/shared/shift/ShiftRestService.java, employee-rostering-webapp/src/test/java/org/optaweb/employeerostering/webapp/rotation/RotationRestServiceIT.java, employee-rostering-webapp/src/test/java/org/optaweb/employeerostering/webapp/shift/ShiftRestServiceIT.java
This PR only addresses PLANNER-1224; Need to create an "Edit ShiftTemplate" form to address the remaining issues in PLANNER-1324.
=> PLANNER-1224: Remove Save Button and Update Rotation REST Service API

.travis.yml, travis-sonarcloud.sh
Enables analysis of PRs and daily analysis of master branch (need to be configured in travis after this PR is merged)
=> Enable PR analysis in SonarCloud

employee-rostering-webapp/pom.xml
- replace javax:javaee-api with JBoss Specs
- declare test dependencies
=> Clean up webapp POM

employee-rostering-frontend/README.adoc, employee-rostering-frontend/src/domain/Spot.tsx, employee-rostering-frontend/src/store/skill/operations.ts, employee-rostering-frontend/src/store/skill/skill.test.ts, employee-rostering-frontend/src/store/spot/actions.ts, employee-rostering-frontend/src/store/spot/index.ts, employee-rostering-frontend/src/store/spot/operations.ts, employee-rostering-frontend/src/store/spot/reducers.ts, employee-rostering-frontend/src/store/spot/spot.test.ts, employee-rostering-frontend/src/store/spot/types.ts, employee-rostering-frontend/src/store/store.ts, employee-rostering-frontend/src/store/tenant/operations.ts, employee-rostering-frontend/src/store/tenant/tenant.test.ts, employee-rostering-frontend/src/store/types.ts, employee-rostering-frontend/src/ui/App.tsx, employee-rostering-frontend/src/ui/__snapshots__/App.test.tsx.snap, employee-rostering-frontend/src/ui/components/DataTable.test.tsx, employee-rostering-frontend/src/ui/components/DataTable.tsx, employee-rostering-frontend/src/ui/components/MultiTypeaheadSelectInput.test.tsx, employee-rostering-frontend/src/ui/components/MultiTypeaheadSelectInput.tsx, employee-rostering-frontend/src/ui/components/__snapshots__/DataTable.test.tsx.snap, employee-rostering-frontend/src/ui/components/__snapshots__/MultiTypeaheadSelectInput.test.tsx.snap, employee-rostering-frontend/src/ui/header/Navigation.tsx, employee-rostering-frontend/src/ui/header/__snapshots__/Navigation.test.tsx.snap, employee-rostering-frontend/src/ui/pages/skill/SkillsPage.test.tsx, employee-rostering-frontend/src/ui/pages/skill/SkillsPage.tsx, employee-rostering-frontend/src/ui/pages/spot/SpotsPage.test.tsx, employee-rostering-frontend/src/ui/pages/spot/SpotsPage.tsx, employee-rostering-frontend/src/ui/pages/spot/__snapshots__/SpotsPage.test.tsx.snap
=> PLANNER-1511: Add Spots Page

employee-rostering-frontend/src/domain/Contract.tsx, employee-rostering-frontend/src/store/contract/actions.ts, employee-rostering-frontend/src/store/contract/contract.test.ts, employee-rostering-frontend/src/store/contract/index.ts, employee-rostering-frontend/src/store/contract/operations.ts, employee-rostering-frontend/src/store/contract/reducers.ts, employee-rostering-frontend/src/store/contract/types.ts, employee-rostering-frontend/src/store/rest/RestTestUtils.ts, employee-rostering-frontend/src/store/rest/__mocks__/RestServiceClient.ts, employee-rostering-frontend/src/store/skill/operations.ts, employee-rostering-frontend/src/store/skill/skill.test.ts, employee-rostering-frontend/src/store/spot/operations.ts, employee-rostering-frontend/src/store/spot/spot.test.ts, employee-rostering-frontend/src/store/store.ts, employee-rostering-frontend/src/store/tenant/operations.ts, employee-rostering-frontend/src/store/tenant/tenant.test.ts, employee-rostering-frontend/src/store/types.ts, employee-rostering-frontend/src/ui/App.tsx, employee-rostering-frontend/src/ui/__snapshots__/App.test.tsx.snap, employee-rostering-frontend/src/ui/components/OptionalInput.test.tsx, employee-rostering-frontend/src/ui/components/OptionalInput.tsx, employee-rostering-frontend/src/ui/components/__snapshots__/OptionalInput.test.tsx.snap, employee-rostering-frontend/src/ui/header/Navigation.tsx, employee-rostering-frontend/src/ui/header/__snapshots__/Navigation.test.tsx.snap, employee-rostering-frontend/src/ui/pages/contract/ContractsPage.test.tsx, employee-rostering-frontend/src/ui/pages/contract/ContractsPage.tsx, employee-rostering-frontend/src/ui/pages/contract/__snapshots__/ContractsPage.test.tsx.snap, employee-rostering-frontend/src/ui/pages/index.ts
=> PLANNER-1512: Add Contracts Page

employee-rostering-backend/src/main/java/org/optaweb/employeerostering/service/tenant/TenantController.java, employee-rostering-backend/src/test/java/org/optaweb/employeerostering/tenant/TenantRestControllerTest.java
Fix `deleteTenant()` HTTP request type to keep consistent with old backend.
=> *IMPORTANT FIX* Fix delete Tenant method request type

employee-rostering-frontend/src/ui/pages/availability/EditAvailabilityModal.test.tsx, employee-rostering-frontend/src/ui/pages/availability/EditAvailabilityModal.tsx, employee-rostering-frontend/src/ui/pages/shift/EditShiftModal.test.tsx, employee-rostering-frontend/src/ui/pages/shift/EditShiftModal.tsx
Depends on https://github.com/kiegroup/optaweb-employee-rostering/pull/289
=> PLANNER-1621: Fix URL when adding Shifts

employee-rostering-backend/pom.xml, employee-rostering-distribution/pom.xml, employee-rostering-frontend/package-lock.json, employee-rostering-frontend/package.json, pom.xml
Identified and fixed some POM problems.
It's not perfect yet, some things still remain like:
- Checkstyle and Jacoco duplications,
- WildFly, persistence and Cargo configuration leftovers.
but let's take it step by step.
=> Clean up POMs

employee-rostering-frontend/src/ui/components/MultiTypeaheadSelectInput.test.tsx, employee-rostering-frontend/src/ui/components/MultiTypeaheadSelectInput.tsx, employee-rostering-frontend/src/ui/components/TypeaheadSelectInput.test.tsx, employee-rostering-frontend/src/ui/components/TypeaheadSelectInput.tsx, employee-rostering-frontend/src/ui/components/__snapshots__/MultiTypeaheadSelectInput.test.tsx.snap, employee-rostering-frontend/src/ui/components/__snapshots__/TypeaheadSelectInput.test.tsx.snap
=> Fix select filters

employee-rostering-frontend/pom.xml
=> BXMSPROD-560 lock-treatment-tool added to Maven build

employee-rostering-frontend/cypress.json, employee-rostering-frontend/cypress/.eslintrc.json, employee-rostering-frontend/cypress/.gitignore, employee-rostering-frontend/cypress/fixtures/example.json, employee-rostering-frontend/cypress/integration/newTenantBasicWorkflow.js, employee-rostering-frontend/cypress/plugins/index.js, employee-rostering-frontend/package-lock.json, employee-rostering-frontend/package.json, employee-rostering-frontend/src/store/admin/admin.test.ts, employee-rostering-frontend/src/store/admin/operations.ts, employee-rostering-frontend/src/ui/components/ConfirmDialog.test.tsx, employee-rostering-frontend/src/ui/components/ConfirmDialog.tsx, employee-rostering-frontend/src/ui/components/__snapshots__/ConfirmDialog.test.tsx.snap, employee-rostering-frontend/src/ui/header/Toolbar.tsx, employee-rostering-frontend/src/ui/header/__snapshots__/Toolbar.test.tsx.snap, employee-rostering-frontend/src/ui/pages/admin/AdminPage.test.tsx, employee-rostering-frontend/src/ui/pages/admin/AdminPage.tsx, employee-rostering-frontend/src/ui/pages/admin/NewTenantFormModal.tsx, employee-rostering-frontend/src/ui/pages/admin/__snapshots__/AdminPage.test.tsx.snap, employee-rostering-frontend/src/ui/pages/admin/__snapshots__/NewTenantFormModal.test.tsx.snap, employee-rostering-frontend/translations/en/AdminPage.yaml, employee-rostering-frontend/translations/en/Alerts.yaml, employee-rostering-frontend/translations/en/ConfirmDialog.yaml
Test creates a new tenant, and for that tenant:
- create a new skill
- create two spots (one requiring skill, the other does not)
- create a contract
- create two employees (one with skill, one without)
- create one shift for each spot
- verify the correct employee is assigned to the correct spot after solving for 5 seconds
=> PLANNER-1429: Add Application Reset button and Cypress test.

employee-rostering-docs/src/main/asciidoc/Features/Features-chapter.adoc, employee-rostering-docs/src/main/asciidoc/Features/H2Database/H2Database-section.adoc, employee-rostering-docs/src/main/asciidoc/Features/RestAPI/RestAPI-section.adoc, employee-rostering-docs/src/main/asciidoc/Introduction/BuildAndRun/BuildAndRun-section.adoc, employee-rostering-docs/src/main/asciidoc/Introduction/Introduction-chapter.adoc, employee-rostering-docs/src/main/asciidoc/index.adoc
- Add Build and Run section
- Add Features chapter with H2 Database and Swagger sections
=> PLANNER-1680: Update AsciiDocs

.travis.yml, README.adoc, employee-rostering-distribution/pom.xml, employee-rostering-frontend/cypress.json
- starts the distribution as a separate process
- runs cypress tests from a docker container to isolate its dependencies from the test environment
=> PLANNER-1708 Run Cypress tests in CI

employee-rostering-frontend/package-lock.json, employee-rostering-frontend/package.json, employee-rostering-frontend/pom.xml
BXMSPROD-597
* lock-treatment-tool added to dev-dependencies
* locktt script added
* pom execution changed to npm run locktt
=> BXMSPROD-597: frontend project locktt execution improved

employee-rostering-backend/README.adoc, employee-rostering-docs/src/main/asciidoc/Features/H2Database/H2Database-section.adoc, employee-rostering-docs/src/main/asciidoc/Introduction/BuildAndRun/BuildAndRun-section.adoc
Minor fixes to build instructions and h2database config in community docs.
=> Update community docs

employee-rostering-frontend/package-lock.json, employee-rostering-frontend/package.json, employee-rostering-frontend/src/setupTests.ts
A continuation of https://github.com/kiegroup/optaweb-employee-rostering/pull/339
=> PLANNER-1729: Made the application builds on Windows 

employee-rostering-backend/pom.xml, employee-rostering-benchmark/pom.xml, pom.xml
Jira: https://issues.jboss.org/browse/PLANNER-1733
=> PLANNER-1733: Remove redundant POM properties

employee-rostering-backend/pom.xml, employee-rostering-backend/src/test/java/org/optaweb/employeerostering/contract/ContractServiceTest.java, employee-rostering-backend/src/test/java/org/optaweb/employeerostering/employee/EmployeeServiceTest.java, employee-rostering-backend/src/test/java/org/optaweb/employeerostering/rotation/RotationServiceTest.java, employee-rostering-backend/src/test/java/org/optaweb/employeerostering/shift/ShiftServiceTest.java, employee-rostering-backend/src/test/java/org/optaweb/employeerostering/skill/SkillServiceTest.java, employee-rostering-backend/src/test/java/org/optaweb/employeerostering/spot/SpotServiceTest.java, employee-rostering-benchmark/pom.xml, pom.xml
Depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1086
=> Remove Spring Boot dependency management

employee-rostering-frontend/src/ui/header/Header.test.tsx, employee-rostering-frontend/src/ui/header/Header.tsx, employee-rostering-frontend/src/ui/header/__snapshots__/Header.test.tsx.snap
Fixes:
```
Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.
in a (at Header.tsx:28)
```
=> Fix <a> inside <a> error

employee-rostering-frontend/pom.xml
=> [7.30.x] RHDM-1129 locktt execution added to productized profile, prepare-package phase (backport)

pom.xml
Should have been removed in 5f2ed9e95d6f.
=> Remove obsolete code coverage profile

employee-rostering-backend/Dockerfile
Replication of https://github.com/kiegroup/optaweb-vehicle-routing/pull/259.
=> PLANNER-1813: Use UBI-based image for backend

optaweb-employee-rostering-docs/pom.xml
https://issues.redhat.com/browse/PLANNER-1839
- kiegroup/droolsjbpm-build-bootstrap/pull/1192
- kiegroup/kie-docs/pull/2200 (optional)
- kiegroup/optaplanner/pull/696
- kiegroup/optaweb-employee-rostering/pull/395
- kiegroup/optaweb-vehicle-routing/pull/268
=> PLANNER-1839: Have Asciidoctor managed by kie-parent

optaweb-employee-rostering-backend/pom.xml, optaweb-employee-rostering-backend/src/test/java/org/optaweb/employeerostering/contract/ContractServiceTest.java, optaweb-employee-rostering-backend/src/test/java/org/optaweb/employeerostering/employee/EmployeeServiceTest.java, optaweb-employee-rostering-backend/src/test/java/org/optaweb/employeerostering/rotation/RotationServiceTest.java, optaweb-employee-rostering-backend/src/test/java/org/optaweb/employeerostering/shift/ShiftServiceTest.java, optaweb-employee-rostering-backend/src/test/java/org/optaweb/employeerostering/skill/SkillServiceTest.java, optaweb-employee-rostering-backend/src/test/java/org/optaweb/employeerostering/spot/SpotServiceTest.java, optaweb-employee-rostering-benchmark/pom.xml
Merge with:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1196
https://github.com/kiegroup/optaplanner/pull/701
https://github.com/kiegroup/jbpm-work-items/pull/124
https://github.com/kiegroup/optaweb-vehicle-routing/pull/270
=> [7.33.x] RHPAM-2734: Minor fixes for downgrade to Spring Boot 2.1.12

optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/domain/shift/view/ShiftView.java, optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/domain/violation/NoBreakViolation.java, optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/service/common/IndictmentUtils.java, optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/service/common/generator/StringDataGenerator.java, optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/service/roster/RosterGenerator.java, optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/service/shift/ShiftService.java, optaweb-employee-rostering-frontend/public/assets/translations/en/EditShiftModal.yaml, optaweb-employee-rostering-frontend/public/assets/translations/en/ShiftEvent.yaml, optaweb-employee-rostering-frontend/src/domain/Employee.tsx, optaweb-employee-rostering-frontend/src/domain/Shift.ts, optaweb-employee-rostering-frontend/src/domain/ShiftView.ts, optaweb-employee-rostering-frontend/src/domain/indictment/NoBreakViolation.ts, optaweb-employee-rostering-frontend/src/store/roster/operations.ts, optaweb-employee-rostering-frontend/src/ui/components/calendar/ReactBigCalendarOverrides.css, optaweb-employee-rostering-frontend/src/ui/pages/employee/__snapshots__/EmployeePage.test.tsx.snap, optaweb-employee-rostering-frontend/src/ui/pages/shift/EditShiftModal.test.tsx, optaweb-employee-rostering-frontend/src/ui/pages/shift/EditShiftModal.tsx, optaweb-employee-rostering-frontend/src/ui/pages/shift/ShiftEvent.tsx, optaweb-employee-rostering-frontend/src/ui/pages/shift/__snapshots__/EditShiftModal.test.tsx.snap, optaweb-employee-rostering-frontend/src/ui/pages/shift/__snapshots__/ShiftEvent.test.tsx.snap
Depends on https://github.com/kiegroup/optaweb-employee-rostering/pull/420
=> Add original employee, required skill set to shift form and new indictment

optaweb-employee-rostering-backend/pom.xml, optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/domain/common/DateTimeUtils.java, optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/domain/shift/Shift.java, optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/domain/tenant/RosterConstraintConfiguration.java, optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/service/common/IndictmentUtils.java, optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/service/solver/EmployeeRosteringConstraintProvider.java, optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/service/solver/LoadBalancingHourCounter.java, optaweb-employee-rostering-backend/src/main/resources/org/optaweb/employeerostering/service/solver/employeeRosteringScoreRules.drl, optaweb-employee-rostering-backend/src/main/resources/solverConfig.xml, optaweb-employee-rostering-backend/src/test/java/org/optaweb/employeerostering/solver/SolverTest.java, optaweb-employee-rostering-benchmark/pom.xml, optaweb-employee-rostering-benchmark/src/main/resources/employeeRosteringBenchmarkConfig.xml, optaweb-employee-rostering-distribution/pom.xml, optaweb-employee-rostering-docs/pom.xml, optaweb-employee-rostering-frontend/pom.xml, optaweb-employee-rostering-standalone/pom.xml, pom.xml
Provides Constraint Streams as an alternative scoring function.
Does not replace DRL.
=> PLANNER-1936 ConstraintProvider for Employee Rostering

pom.xml
Merge with: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1350
=> Manage postgresql version with kie-parent

optaweb-employee-rostering-backend/pom.xml
Parent PR https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1347
=> BXMSPROD-685: added exclusion for enforcer ban-duplicated-classes

optaweb-employee-rostering-frontend/src/ui/components/ServerSideExceptionDialog.tsx, optaweb-employee-rostering-frontend/src/ui/components/__snapshots__/ServerSideExceptionDialog.test.tsx.snap
=> Issue #274: Use uuid for generating keys in stack traces

optaweb-employee-rostering-frontend/src/ui/components/calendar/Schedule.tsx
`dropLocation.end` is already the correct date, no need to add one extra day
=> Fix issue when drag full day availability time range

optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/service/roster/RosterService.java
=> Rebuild the roster instead of fetching a stale roster from the solver if the Solver is not solving (#467)

optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/service/roster/RosterController.java, optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/service/roster/RosterService.java, optaweb-employee-rostering-backend/src/test/java/org/optaweb/employeerostering/roster/RosterRestControllerTest.java, optaweb-employee-rostering-frontend/public/assets/translations/en/Alerts.yaml, optaweb-employee-rostering-frontend/public/assets/translations/en/ProvisionShiftsModal.yaml, optaweb-employee-rostering-frontend/public/assets/translations/en/ShiftRosterPage.yaml, optaweb-employee-rostering-frontend/src/store/roster/operations.ts, optaweb-employee-rostering-frontend/src/ui/pages/rotation/RotationPage.test.tsx, optaweb-employee-rostering-frontend/src/ui/pages/shift/ProvisionShiftsModal.test.tsx, optaweb-employee-rostering-frontend/src/ui/pages/shift/ProvisionShiftsModal.tsx, optaweb-employee-rostering-frontend/src/ui/pages/shift/ShiftRosterPage.tsx, optaweb-employee-rostering-frontend/src/ui/pages/shift/__snapshots__/ProvisionShiftsModal.test.tsx.snap, optaweb-employee-rostering-frontend/src/ui/pages/shift/__snapshots__/ShiftRosterPage.test.tsx.snap
=> PLANNER-1283: Add Provision Operation

Jenkinsfile
https://issues.redhat.com/browse/PLANNER-2202
<details>
<summary>
</summary>
</details>
=> PLANNER-2202 Create PR pipelines for Optawebs

optaweb-employee-rostering-backend/pom.xml, optaweb-employee-rostering-benchmark/pom.xml, optaweb-employee-rostering-distribution/pom.xml, optaweb-employee-rostering-docs/pom.xml, optaweb-employee-rostering-frontend/pom.xml, optaweb-employee-rostering-standalone/pom.xml, pom.xml
https://issues.redhat.com/browse/PLANNER-2243
<details>
<summary>
</summary>
</details>
=> PLANNER-2243 Upgrade project version to 8.1.0-SNAPSHOT

build/release/upload_distribution.sh
Tested locally and results verified via FileZilla on the remote server.
https://issues.redhat.com/browse/PLANNER-2216
A similar script for Vehicle Routing: https://github.com/kiegroup/optaweb-vehicle-routing/pull/403
<details>
<summary>
</summary>
</details>
=> PLANNER-2216 Create a distribution upload script

optaweb-employee-rostering-backend/pom.xml, optaweb-employee-rostering-benchmark/pom.xml, pom.xml
https://issues.redhat.com/browse/PLANNER-2232
<details>
<summary>
</summary>
</details>
=> PLANNER-2232: Remove formatter plugin configuration

optaweb-employee-rostering-backend/pom.xml, optaweb-employee-rostering-benchmark/pom.xml, optaweb-employee-rostering-distribution/pom.xml, optaweb-employee-rostering-docs/pom.xml, optaweb-employee-rostering-frontend/pom.xml, optaweb-employee-rostering-standalone/pom.xml, pom.xml
https://issues.redhat.com/browse/PLANNER-2243
https://github.com/kiegroup/optaweb-vehicle-routing/pull/407
<details>
<summary>
</summary>
</details>
=> PLANNER-2243 Release version 8.0.0.Final

optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/domain/employee/Employee.java, optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/domain/shift/Shift.java, optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/domain/violation/DesiredTimeslotForEmployeeReward.java, optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/domain/violation/PublishedShiftReassignedPenalty.java, optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/domain/violation/RequiredSkillViolation.java, optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/domain/violation/RotationViolationPenalty.java, optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/domain/violation/ShiftEmployeeConflict.java, optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/domain/violation/UnassignedShiftPenalty.java, optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/domain/violation/UnavailableEmployeeViolation.java, optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/domain/violation/UndesiredTimeslotForEmployeePenalty.java
<details>
<summary>
</summary>
</details>
=> Remove unused methods, add missing Overrides

optaweb-employee-rostering-backend/pom.xml, optaweb-employee-rostering-benchmark/pom.xml, optaweb-employee-rostering-distribution/pom.xml, optaweb-employee-rostering-docs/pom.xml, optaweb-employee-rostering-frontend/pom.xml, optaweb-employee-rostering-standalone/pom.xml, pom.xml
Due to branch 8.1.x created
Related PRs:
- https://github.com/kiegroup/optaplanner/pull/1073
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/412
- https://github.com/kiegroup/optaweb-employee-rostering/pull/547
- https://github.com/kiegroup/optaplanner-quickstarts/pull/37
=> Updated version to 8.2.0-SNAPSHOT

optaweb-employee-rostering-frontend/cypress/integration/newTenantBasicWorkflow.js
Cherry pick of 
https://github.com/kiegroup/optaweb-employee-rostering/pull/549
<details>
<summary>
</summary>
</details>
=> Propagate ERP fixes for integration tests for 7.48.x from master

optaweb-employee-rostering-frontend/cypress/integration/newTenantBasicWorkflow.js
Cherry pick 
5d00c37c
+
Remove reset application
<details>
<summary>
</summary>
</details>
=> Propagate ERP fixes for integration tests for 7.x from master

optaweb-employee-rostering-backend/pom.xml, optaweb-employee-rostering-benchmark/pom.xml, optaweb-employee-rostering-distribution/pom.xml, optaweb-employee-rostering-docs/pom.xml, optaweb-employee-rostering-frontend/pom.xml, optaweb-employee-rostering-standalone/pom.xml, pom.xml
https://github.com/kiegroup/optaplanner/pull/1120
https://github.com/kiegroup/optaplanner-quickstarts/pull/47
https://github.com/kiegroup/optaweb-vehicle-routing/pull/418
https://github.com/kiegroup/optaweb-employee-rostering/pull/554
https://github.com/kiegroup/kogito-examples/pull/537
https://github.com/kiegroup/kogito-apps/pull/612
<details>
<summary>
</summary>
* for an <b>upstream build</b> …
=> Upgrade version to 8.3.0-SNAPSHOT

.github/workflows/pull_request.yml
https://issues.redhat.com/browse/BXMSPROD-1202
- https://github.com/kiegroup/optaweb-employee-rostering/pull/560
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/421
- https://github.com/kiegroup/kie-wb-distributions/pull/1083
- https://github.com/kiegroup/droolsjbpm-integration/pull/2392
- https://github.com/kiegroup/optaweb-employee-rostering/pull/561
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/422
<details>
<summary>
</summary>
* for a <b>full production downstream …
=> BXMSPROD-1202 ubuntu-latest to ubuntu-18.04 (master)

.github/workflows/pull_request.yml
https://issues.redhat.com/browse/BXMSPROD-1202
- https://github.com/kiegroup/optaweb-employee-rostering/pull/560
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/421
- https://github.com/kiegroup/kie-wb-distributions/pull/1083
- https://github.com/kiegroup/droolsjbpm-integration/pull/2392
- https://github.com/kiegroup/optaweb-employee-rostering/pull/561
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/422
<details>
<summary>
</summary>
* for a <b>full production downstream …
=> BXMSPROD-1202 ubuntu-latest to ubuntu-18.04 (7.x)

.github/workflows/pull_request.yml
<details>
<summary>
</summary>
</details>
=> BXMSPROD-1202 ubuntu-latest to ubuntu-18.04 (master2)

optaweb-employee-rostering-backend/pom.xml, optaweb-employee-rostering-benchmark/pom.xml, optaweb-employee-rostering-standalone/pom.xml, pom.xml
Fixes the build broken by https://github.com/kiegroup/optaplanner/pull/1141
Error assembling JAR: Invalid automatic module name: ''
<details>
<summary>
</summary>
</details>
=> Fix broken build

.github/workflows/pull_request.yml, .mvn/extensions.xml
https://issues.redhat.com/browse/BXMSPROD-1216
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/438
- https://github.com/kiegroup/optaweb-employee-rostering/pull/580
=> BXMSPROD-1216 .mvn/extensions.xml takari (master)

optaweb-employee-rostering-frontend/cypress/integration/newTenantBasicWorkflow.js, optaweb-employee-rostering-frontend/src/ui/components/DataTable.tsx, optaweb-employee-rostering-frontend/src/ui/components/__snapshots__/DataTable.test.tsx.snap, optaweb-employee-rostering-frontend/src/ui/pages/employee/EmployeesPage.tsx
<details>
<summary>
</summary>
</details>
=> Update labels in Cypress tests; autofill short id for Employee

README.adoc, optaweb-employee-rostering-backend/README.adoc, optaweb-employee-rostering-backend/pom.xml, optaweb-employee-rostering-benchmark/pom.xml, optaweb-employee-rostering-benchmark/src/main/java/org/optaweb/employeerostering/OptaWebEmployeeRosteringBenchmarkApplication.java, optaweb-employee-rostering-benchmark/src/main/resources/application.properties, optaweb-employee-rostering-docs/src/main/asciidoc/Features/H2Database/H2Database-section.adoc, optaweb-employee-rostering-docs/src/main/asciidoc/Introduction/BuildAndRun/BuildAndRun-section.adoc, optaweb-employee-rostering-docs/src/main/asciidoc/Introduction/SystemProperties/SystemProperties-section.adoc, optaweb-employee-rostering-docs/src/main/asciidoc/ProjectStructure/ProjectStructure-section.adoc
<details>
<summary>
</summary>
</details>
=> Update documentation, fix benchmark

optaweb-employee-rostering-backend/.gitignore
<details>
<summary>
</summary>
</details>
=> Ignore Panache archive marker

.github/workflows/pull_request.yml
https://issues.redhat.com/browse/BXMSPROD-1390
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/519
- https://github.com/kiegroup/optaweb-employee-rostering/pull/645
<details>
<summary>
</summary>
</details>
=> [master] BXMSPROD-1390 github actions flows concurrency

.github/workflows/pull_request.yml, README.adoc, pom.xml
**PLEASE DO NOT MERGE. THIS WILL BE DONE WHEN `master` will be renamed as `main`**
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/188
- https://github.com/kiegroup/kogito-runtimes/pull/1365
- https://github.com/kiegroup/optaplanner/pull/1372
- https://github.com/kiegroup/optaweb-employee-rostering/pull/660
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/532
- https://github.com/kiegroup/optaplanner-quickstarts/pull/144
- https://github.com/kiegroup/kogito-apps/pull/882
- https://github.com/kiegroup/kogito-examples/pull/729
- https://github.com/kiegroup/kogito-images/pull/516
- https://github.com/kiegroup/kogito-operator/pull/905
- https://github.com/kiegroup/rhpam-kogito-operator/pull/44
<details>
<summary> …
=> BXMSPROD-1265: Conscious language initiative

.github/workflows/pull_request.yml, README.adoc, pom.xml
https://github.com/kiegroup/optaplanner/pull/1466
https://github.com/kiegroup/optaweb-employee-rostering/pull/663
https://github.com/kiegroup/optaweb-vehicle-routing/pull/536
<!--
Thank you for submitting this pull request.
<details>
<summary>
</summary>
</details>
=> BXMSPROD-1265: master to main leftovers

optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/domain/shift/Shift.java
https://issues.redhat.com/browse/PLANNER-2504
<details>
<summary>
</summary>
</details>
=> PLANNER-2504 remove final modifier (workaround)

optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/domain/shift/Shift.java
Cherry-pick of https://github.com/kiegroup/optaweb-employee-rostering/pull/671
<details>
<summary>
</summary>
</details>
=> [8.10.x] PLANNER-2504 remove final modifier (workaround)

optaweb-employee-rostering-backend/pom.xml, optaweb-employee-rostering-benchmark/pom.xml, optaweb-employee-rostering-standalone/pom.xml
**JIRA**: 
[JBPM-9659](https://issues.redhat.com/browse/JBPM-9659)
**Related PRs*: 
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1693
https://github.com/kiegroup/kie-soup/pull/216
https://github.com/kiegroup/droolsjbpm-knowledge/pull/543
https://github.com/kiegroup/drools/pull/3757
https://github.com/kiegroup/optaplanner/pull/1463
https://github.com/kiegroup/lienzo-tests/pull/124
https://github.com/kiegroup/appformer/pull/1163
https://github.com/kiegroup/kie-uberfire-extensions/pull/122
https://github.com/kiegroup/jbpm/pull/1974
https://github.com/kiegroup/kie-jpmml-integration/pull/62
https://github.com/kiegroup/droolsjbpm-integration/pull/2539
https://github.com/kiegroup/kie-wb-playground/pull/115
https://github.com/kiegroup/kie-wb-common/pull/3660 …
=> JBPM-9659: Upgrade deployments to WildFly 23

.github/workflows/ci.yml, .github/workflows/pull_request.yml
**Thank you for submitting this pull request**
**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1475
**referenced Pull Requests**: 
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1770
* https://github.com/kiegroup/kie-soup/pull/228
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/549
* https://github.com/kiegroup/drools/pull/3835
* https://github.com/kiegroup/optaplanner/pull/1577
* https://github.com/kiegroup/lienzo-core/pull/152
* https://github.com/kiegroup/lienzo-tests/pull/126
* https://github.com/kiegroup/appformer/pull/1197
* https://github.com/kiegroup/kie-uberfire-extensions/pull/124
* https://github.com/kiegroup/jbpm/pull/2024
* https://github.com/kiegroup/kie-jpmml-integration/pull/65
* https://github.com/kiegroup/droolsjbpm-integration/pull/2607
* …
=> BXMSPROD-1475 maven version

.github/workflows/pull_request.yml
https://issues.redhat.com/browse/BXMSPROD-1543
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1819
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case …
=> BXMSPROD-1543 to point to kogito-pipelines composite actions

.github/workflows/pull_request.yml
<details>
<summary>
</summary> …
=> [7.x] BXMSPROD-1543 to align composite-actions with the ones from kogito-pipelines

.github/workflows/pull_request.yml
https://github.com/kiegroup/optaweb-vehicle-routing/pull/602
=>  BXMSPROD-1542 definition-file eval expression 

.github/workflows/pull_request.yml
https://github.com/kiegroup/optaweb-vehicle-routing/pull/602
=> [8.14.x] BXMSPROD-1542 definition-file eval expression

.github/workflows/pull_request.yml
https://github.com/kiegroup/optaweb-vehicle-routing/pull/602
=> [8.11.x] BXMSPROD-1542 definition-file eval expression

optaweb-employee-rostering-frontend/package.json, optaweb-employee-rostering-frontend/pom.xml, pom.xml
https://issues.redhat.com/browse/BXMSPROD-1558
https://github.com/kiegroup/appformer/pull/1217
https://github.com/kiegroup/kie-wb-common/pull/3709
https://github.com/kiegroup/kogito-apps/pull/1141
https://github.com/kiegroup/kogito-editors-java/pull/184
https://github.com/kiegroup/optaweb-employee-rostering/pull/730
https://github.com/kiegroup/optaweb-vehicle-routing/pull/614
https://github.com/kiegroup/process-migration-service/pull/37
https://github.com/kiegroup/lock-treatment-tool/pull/3
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1840
https://github.com/kiegroup/kie-jenkins-scripts/pull/1175
=> BXMSPROD-1558 install lock-treatment-tool exec

pom.xml
- Upgrade frontend-maven-plugin `1.8.0` -> `1.11.3`, which correctly installs npm on Apple SIlicon.
https://github.com/kiegroup/optaweb-employee-rostering/issues/608
Same version in optaweb-vehicle-routing
https://github.com/kiegroup/optaweb-vehicle-routing/pull/616
<details>
<summary>
</summary>
[build-chain …
=> Upgrade frontend-maven-plugin for Apple Silicon support

optaweb-employee-rostering-backend/.gitignore
Ignoring files created (and ignored) on main makes it more comfortable
to switch between branches. Without ignoring main-ignored files also on
7.x, when you switch to 7.x, `git status` suddenly reports untracked
files, creating unnecessary noise.
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/622
- https://github.com/kiegroup/optaweb-employee-rostering/pull/737
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross …
=> Ignore new files created on main

optaweb-employee-rostering-frontend/package.json
<details>
<summary>
</summary> …
=> Keep dependencies sorted

optaweb-employee-rostering-backend/pom.xml, optaweb-employee-rostering-benchmark/pom.xml, optaweb-employee-rostering-distribution/pom.xml, optaweb-employee-rostering-docs/pom.xml, optaweb-employee-rostering-frontend/pom.xml, optaweb-employee-rostering-standalone/pom.xml, pom.xml
- https://github.com/kiegroup/drools/pull/4286
- https://github.com/kiegroup/optaplanner/pull/1907
- https://github.com/kiegroup/optaplanner-quickstarts/pull/316
- https://github.com/kiegroup/optaweb-employee-rostering/pull/784
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/674
- https://github.com/kiegroup/kogito-apps/pull/1291
- https://github.com/kiegroup/kogito-examples/pull/1205
- https://github.com/kiegroup/kogito-runtimes/pull/2121
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain …
=> bumped up to next 8.20.0-SNAPSHOT

README.adoc
<details>
<summary>
</summary> …
=> Link to a newer version of the employee rostering video

optaweb-employee-rostering-frontend/.eslintrc.json, optaweb-employee-rostering-frontend/package-lock.json, optaweb-employee-rostering-frontend/package.json, optaweb-employee-rostering-frontend/src/ui/App.tsx
<details>
<summary>
</summary> …
=> Clean up after license headers removal

.github/workflows/full-downstream.yml, .github/workflows/pull_request.yml
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/543
- https://github.com/kiegroup/kogito-runtimes/pull/2317
- https://github.com/kiegroup/kogito-apps/pull/1407
- https://github.com/kiegroup/kogito-examples/pull/1324
- https://github.com/kiegroup/drools/pull/4525
- https://github.com/kiegroup/optaplanner/pull/2063
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/728
- https://github.com/kiegroup/optaweb-employee-rostering/pull/841
=> [KOGITO-7504] Update Maven to 3.8.6

optaweb-employee-rostering-frontend/src/ui/components/WeekPicker.css
<details>
<summary>
</summary> …
=> PLANNER-2747 Fix ERP UI resolution shift

optaweb-employee-rostering-frontend/package-lock.json, optaweb-employee-rostering-frontend/package.json
https://issues.redhat.com/browse/RHPAM-4448
Related PRs:
* https://github.com/kiegroup/optaweb-employee-rostering/pull/849
* https://github.com/kiegroup/optaweb-employee-rostering/pull/850
* https://github.com/kiegroup/optaweb-employee-rostering/pull/851
* https://github.com/kiegroup/optaweb-employee-rostering/pull/852
=> [7.67.x] RHPAM-4448 Upgrade moment to 2.29.4

optaweb-employee-rostering-frontend/package-lock.json, optaweb-employee-rostering-frontend/package.json
https://issues.redhat.com/browse/RHPAM-4448
Related PRs:
* https://github.com/kiegroup/optaweb-employee-rostering/pull/849
* https://github.com/kiegroup/optaweb-employee-rostering/pull/850
* https://github.com/kiegroup/optaweb-employee-rostering/pull/851
* https://github.com/kiegroup/optaweb-employee-rostering/pull/852
=> [7.x] RHPAM-4448 Upgrade moment to 2.29.4

optaweb-employee-rostering-frontend/package-lock.json, optaweb-employee-rostering-frontend/package.json
https://issues.redhat.com/browse/RHPAM-4530
related PRs:
* https://github.com/kiegroup/optaweb-employee-rostering/pull/855
* https://github.com/kiegroup/optaweb-employee-rostering/pull/856
* https://github.com/kiegroup/optaweb-employee-rostering/pull/857
=> [7.x] RHPAM-4530 lock-treatment-tool upgraded to 0.2.1 CVE-2021-23383

optaweb-employee-rostering-frontend/pom.xml
https://issues.redhat.com/browse/BXMSPROD-1700
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2111
- https://github.com/kiegroup/appformer/pull/1322
- https://github.com/kiegroup/kie-wb-common/pull/3787
- https://github.com/kiegroup/process-migration-service/pull/84
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/781
- https://github.com/kiegroup/optaweb-employee-rostering/pull/860
=> [BXMSPROD-1700] lock-treatment-tool version property
